import os
import time
import atexit

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
USERS_DIR = os.path.join(SCRIPT_DIR, 'users.txt')
DUNGEON_TREASURE_FILE = os.path.join(SCRIPT_DIR, 'dungeon_treasure.json')
dungeon_treasure = {'money': 0, 'items': []}
GLOBAL_KEY = '__global__'
AUTOSAVE_INTERVAL = 30
autosave_timer = None
last_autosave_time = time.time()

MONSTERS = [
    # D(Common) monsters - Areas 1-20
    {'name': 'Slime', 'hp': 15, 'atk_min': 3, 'atk_max': 6, 'money_min': 2, 'money_max': 7, 'class': 'D(Common)', 'is_boss': False, 'is_super_boss': False, 'drop': {'potion': 0.25, 'slime_gel': 0.4}, 'weight': 18, 'area': 1, 'element': 'nature', 'exp_min': 10, 'exp_max': 25},
    {'name': 'Goblin', 'hp': 20, 'atk_min': 5, 'atk_max': 8, 'money_min': 4, 'money_max': 15, 'class': 'D(Common)', 'is_boss': False, 'is_super_boss': False, 'drop': {'potion': 0.3, 'strength_boost': 0.05, 'goblin_tooth': 0.3}, 'weight': 15, 'area': 1, 'element': 'mana', 'exp_min': 10, 'exp_max': 25},
    {'name': 'Wolf', 'hp': 25, 'atk_min': 6, 'atk_max': 10, 'money_min': 10, 'money_max': 22, 'class': 'D(Common)', 'is_boss': False, 'is_super_boss': False, 'drop': {'potion': 0.2, 'wolf_pelt': 0.3}, 'weight': 14, 'area': 2, 'element': 'nature', 'exp_min': 10, 'exp_max': 25},
    {'name': 'Forest Sprite', 'hp': 30, 'atk_min': 5, 'atk_max': 9, 'money_min': 8, 'money_max': 20, 'class': 'D(Common)', 'is_boss': False, 'is_super_boss': False, 'drop': {'potion': 0.25, 'mana_regen_potion': 0.1, 'crystal_shard': 0.2}, 'weight': 12, 'area': 3, 'element': 'nature', 'exp_min': 10, 'exp_max': 25},
    {'name': 'Skeleton', 'hp': 40, 'atk_min': 8, 'atk_max': 12, 'money_min': 15, 'money_max': 30, 'class': 'D(Common)', 'is_boss': False, 'is_super_boss': False, 'drop': {'potion': 0.25, 'defense_boost': 0.05, 'skeleton_bone': 0.4}, 'weight': 12, 'area': 5, 'element': 'mana', 'exp_min': 15, 'exp_max': 37},
    {'name': 'Orc', 'hp': 60, 'atk_min': 10, 'atk_max': 15, 'money_min': 20, 'money_max': 40, 'class': 'D(Common)', 'is_boss': False, 'is_super_boss': False, 'drop': {'potion': 0.2, 'orc_iron': 0.3}, 'weight': 10, 'area': 7, 'element': 'mana', 'exp_min': 15, 'exp_max': 37},
    {'name': 'Giant Spider', 'hp': 50, 'atk_min': 12, 'atk_max': 18, 'money_min': 25, 'money_max': 45, 'class': 'D(Common)', 'is_boss': False, 'is_super_boss': False, 'drop': {'potion': 0.2, 'crit_boost': 0.05, 'spider_venom': 0.3}, 'weight': 8, 'area': 9, 'element': 'nature', 'exp_min': 15, 'exp_max': 37},
    {'name': 'Dark Bat', 'hp': 35, 'atk_min': 10, 'atk_max': 15, 'money_min': 18, 'money_max': 35, 'class': 'D(Common)', 'is_boss': False, 'is_super_boss': False, 'drop': {'potion': 0.2, 'bat_wing': 0.3}, 'weight': 10, 'area': 11, 'element': 'nature', 'exp_min': 15, 'exp_max': 37},
    
    # C(Rare) monsters - Areas 21-40
    {'name': 'Goblin Shaman', 'hp': 80, 'atk_min': 16, 'atk_max': 24, 'money_min': 10, 'money_max': 25, 'class': 'C(Rare)', 'is_boss': False, 'is_super_boss': False, 'drop': {'mana_regen_potion': 0.1, 'goblin_tooth': 0.2}, 'weight': 8, 'area': 21, 'element': 'mana', 'exp_min': 10, 'exp_max': 25},
    {'name': 'Bandit', 'hp': 160, 'atk_min': 14, 'atk_max': 24, 'money_min': 35, 'money_max': 60, 'class': 'C(Rare)', 'is_boss': False, 'is_super_boss': False, 'drop': {'potion': 0.15, 'crit_boost': 0.04, 'common_magic_pack': 0.15, 'bandit_cloth': 0.3, 'perm_exp_upgrade': 0.1, 'perm_strength_upgrade': 0.1, 'perm_defense_upgrade': 0.1, 'perm_health_upgrade': 0.1, 'perm_mana_upgrade': 0.1, 'perm_crit_chance_upgrade': 0.1, 'perm_mana_regen_upgrade': 0.1, 'perm_lifesteal_upgrade': 0.1, 'perm_lifesteal_chance_upgrade': 0.1}, 'weight': 10, 'area': 25, 'element': 'mana', 'exp_min': 22, 'exp_max': 56},
    {'name': 'Orc Warrior', 'hp': 220, 'atk_min': 16, 'atk_max': 26, 'money_min': 40, 'money_max': 70, 'class': 'C(Rare)', 'is_boss': False, 'is_super_boss': False, 'drop': {'potion': 0.2, 'orc_iron': 0.4, 'strength_boost': 0.1, 'perm_exp_upgrade': 0.1, 'perm_strength_upgrade': 0.1, 'perm_defense_upgrade': 0.1, 'perm_health_upgrade': 0.1, 'perm_mana_upgrade': 0.1, 'perm_crit_chance_upgrade': 0.1, 'perm_mana_regen_upgrade': 0.1, 'perm_lifesteal_upgrade': 0.1, 'perm_lifesteal_chance_upgrade': 0.1}, 'weight': 8, 'area': 27, 'element': 'mana', 'exp_min': 22, 'exp_max': 56},
    {'name': 'Dark Mage', 'hp': 180, 'atk_min': 20, 'atk_max': 30, 'money_min': 50, 'money_max': 80, 'class': 'C(Rare)', 'is_boss': False, 'is_super_boss': False, 'drop': {'potion': 0.25, 'strength_boost': 0.06, 'common_magic_pack': 0.25, 'rare_magic_pack': 0.1, 'dark_essence': 0.2, 'perm_exp_upgrade': 0.1, 'perm_strength_upgrade': 0.1, 'perm_defense_upgrade': 0.1, 'perm_health_upgrade': 0.1, 'perm_mana_upgrade': 0.1, 'perm_crit_chance_upgrade': 0.1, 'perm_mana_regen_upgrade': 0.1, 'perm_lifesteal_upgrade': 0.1, 'perm_lifesteal_chance_upgrade': 0.1}, 'weight': 7, 'area': 29, 'element': 'mana', 'exp_min': 22, 'exp_max': 56},
    {'name': 'Stone Golem', 'hp': 280, 'atk_min': 12, 'atk_max': 20, 'money_min': 45, 'money_max': 75, 'class': 'C(Rare)', 'is_boss': False, 'is_super_boss': False, 'drop': {'potion': 0.2, 'defense_boost': 0.1, 'stone_core': 0.3, 'perm_exp_upgrade': 0.1, 'perm_strength_upgrade': 0.1, 'perm_defense_upgrade': 0.1, 'perm_health_upgrade': 0.1, 'perm_mana_upgrade': 0.1, 'perm_crit_chance_upgrade': 0.1, 'perm_mana_regen_upgrade': 0.1, 'perm_lifesteal_upgrade': 0.1, 'perm_lifesteal_chance_upgrade': 0.1}, 'weight': 6, 'area': 31, 'element': 'nature', 'exp_min': 22, 'exp_max': 56},
    {'name': 'Troll', 'hp': 360, 'atk_min': 24, 'atk_max': 36, 'money_min': 80, 'money_max': 120, 'class': 'C(Rare)', 'is_boss': False, 'is_super_boss': False, 'drop': {'potion': 0.2, 'regen_potion': 0.05, 'common_magic_pack': 0.1, 'rare_magic_pack': 0.05, 'troll_core': 0.3, 'perm_exp_upgrade': 0.1, 'perm_strength_upgrade': 0.1, 'perm_defense_upgrade': 0.1, 'perm_health_upgrade': 0.1, 'perm_mana_upgrade': 0.1, 'perm_crit_chance_upgrade': 0.1, 'perm_mana_regen_upgrade': 0.1, 'perm_lifesteal_upgrade': 0.1, 'perm_lifesteal_chance_upgrade': 0.1}, 'weight': 6, 'area': 33, 'element': 'nature', 'exp_min': 33, 'exp_max': 84},
    {'name': 'Ice Elemental', 'hp': 300, 'atk_min': 30, 'atk_max': 40, 'money_min': 90, 'money_max': 130, 'class': 'C(Rare)', 'is_boss': False, 'is_super_boss': False, 'drop': {'potion': 0.2, 'frozen_heart': 0.3, 'ice_shard': 0.2, 'perm_exp_upgrade': 0.1, 'perm_strength_upgrade': 0.1, 'perm_defense_upgrade': 0.1, 'perm_health_upgrade': 0.1, 'perm_mana_upgrade': 0.1, 'perm_crit_chance_upgrade': 0.1, 'perm_mana_regen_upgrade': 0.1, 'perm_lifesteal_upgrade': 0.1, 'perm_lifesteal_chance_upgrade': 0.1}, 'weight': 5, 'area': 35, 'element': 'ice', 'exp_min': 33, 'exp_max': 84},
    {'name': 'Fire Elemental', 'hp': 280, 'atk_min': 32, 'atk_max': 44, 'money_min': 85, 'money_max': 125, 'class': 'C(Rare)', 'is_boss': False, 'is_super_boss': False, 'drop': {'potion': 0.2, 'fire_essence': 0.3, 'ember': 0.2, 'perm_exp_upgrade': 0.1, 'perm_strength_upgrade': 0.1, 'perm_defense_upgrade': 0.1, 'perm_health_upgrade': 0.1, 'perm_mana_upgrade': 0.1, 'perm_crit_chance_upgrade': 0.1, 'perm_mana_regen_upgrade': 0.1, 'perm_lifesteal_upgrade': 0.1, 'perm_lifesteal_chance_upgrade': 0.1}, 'weight': 5, 'area': 37, 'element': 'fire', 'exp_min': 33, 'exp_max': 84},
    {'name': 'Thunder Bird', 'hp': 260, 'atk_min': 28, 'atk_max': 42, 'money_min': 95, 'money_max': 140, 'class': 'C(Rare)', 'is_boss': False, 'is_super_boss': False, 'drop': {'potion': 0.2, 'thunder_core': 0.3, 'lightning_feather': 0.2, 'perm_exp_upgrade': 0.1, 'perm_strength_upgrade': 0.1, 'perm_defense_upgrade': 0.1, 'perm_health_upgrade': 0.1, 'perm_mana_upgrade': 0.1, 'perm_crit_chance_upgrade': 0.1, 'perm_mana_regen_upgrade': 0.1, 'perm_lifesteal_upgrade': 0.1, 'perm_lifesteal_chance_upgrade': 0.1}, 'weight': 5, 'area': 39, 'element': 'lightning', 'exp_min': 33, 'exp_max': 84},
    
    # B(Mythical) monsters - Areas 41-60
    {'name': 'Dark Knight', 'hp': 480, 'atk_min': 36, 'atk_max': 50, 'money_min': 120, 'money_max': 180, 'class': 'B(Mythical)', 'is_boss': False, 'is_super_boss': False, 'drop': {'potion': 0.15, 'defense_boost': 0.1, 'rare_magic_pack': 0.2, 'dark_essence': 0.3, 'perm_exp_upgrade': 0.12, 'perm_strength_upgrade': 0.12, 'perm_defense_upgrade': 0.12, 'perm_health_upgrade': 0.12, 'perm_mana_upgrade': 0.12, 'perm_crit_chance_upgrade': 0.12, 'perm_mana_regen_upgrade': 0.12, 'perm_lifesteal_upgrade': 0.12, 'perm_lifesteal_chance_upgrade': 0.12}, 'weight': 4, 'area': 41, 'element': 'mana', 'exp_min': 50, 'exp_max': 126},
    {'name': 'Shadow Assassin', 'hp': 400, 'atk_min': 40, 'atk_max': 56, 'money_min': 130, 'money_max': 190, 'class': 'B(Mythical)', 'is_boss': False, 'is_super_boss': False, 'drop': {'potion': 0.15, 'crit_boost': 0.1, 'rare_magic_pack': 0.2, 'shadow_cloak': 0.2, 'perm_exp_upgrade': 0.12, 'perm_strength_upgrade': 0.12, 'perm_defense_upgrade': 0.12, 'perm_health_upgrade': 0.12, 'perm_mana_upgrade': 0.12, 'perm_crit_chance_upgrade': 0.12, 'perm_mana_regen_upgrade': 0.12, 'perm_lifesteal_upgrade': 0.12, 'perm_lifesteal_chance_upgrade': 0.12}, 'weight': 4, 'area': 43, 'element': 'mana', 'exp_min': 50, 'exp_max': 126},
    {'name': 'Arcane Mage', 'hp': 440, 'atk_min': 44, 'atk_max': 60, 'money_min': 140, 'money_max': 200, 'class': 'B(Mythical)', 'is_boss': False, 'is_super_boss': False, 'drop': {'potion': 0.2, 'mana_upgrade_potion': 0.1, 'rare_magic_pack': 0.25, 'mythical_magic_pack': 0.1, 'arcane_tome': 0.2, 'perm_exp_upgrade': 0.12, 'perm_strength_upgrade': 0.12, 'perm_defense_upgrade': 0.12, 'perm_health_upgrade': 0.12, 'perm_mana_upgrade': 0.12, 'perm_crit_chance_upgrade': 0.12, 'perm_mana_regen_upgrade': 0.12, 'perm_lifesteal_upgrade': 0.12, 'perm_lifesteal_chance_upgrade': 0.12}, 'weight': 3, 'area': 45, 'element': 'mana', 'exp_min': 50, 'exp_max': 126},
    {'name': 'Warlock', 'hp': 420, 'atk_min': 42, 'atk_max': 58, 'money_min': 135, 'money_max': 195, 'class': 'B(Mythical)', 'is_boss': False, 'is_super_boss': False, 'drop': {'potion': 0.2, 'curse_scroll': 0.2, 'rare_magic_pack': 0.2, 'mythical_magic_pack': 0.1, 'demon_horn': 0.2, 'perm_exp_upgrade': 0.12, 'perm_strength_upgrade': 0.12, 'perm_defense_upgrade': 0.12, 'perm_health_upgrade': 0.12, 'perm_mana_upgrade': 0.12, 'perm_crit_chance_upgrade': 0.12, 'perm_mana_regen_upgrade': 0.12, 'perm_lifesteal_upgrade': 0.12, 'perm_lifesteal_chance_upgrade': 0.12}, 'weight': 3, 'area': 47, 'element': 'mana', 'exp_min': 50, 'exp_max': 126},
    {'name': 'Ice Giant', 'hp': 600, 'atk_min': 50, 'atk_max': 70, 'money_min': 180, 'money_max': 250, 'class': 'B(Mythical)', 'is_boss': False, 'is_super_boss': False, 'drop': {'potion': 0.2, 'frozen_heart': 0.4, 'mythical_magic_pack': 0.2, 'ice_shard': 0.3, 'perm_exp_upgrade': 0.14, 'perm_strength_upgrade': 0.14, 'perm_defense_upgrade': 0.14, 'perm_health_upgrade': 0.14, 'perm_mana_upgrade': 0.14, 'perm_crit_chance_upgrade': 0.14, 'perm_mana_regen_upgrade': 0.14, 'perm_lifesteal_upgrade': 0.14, 'perm_lifesteal_chance_upgrade': 0.14}, 'weight': 3, 'area': 49, 'element': 'ice', 'exp_min': 75, 'exp_max': 189},
    {'name': 'Phoenix', 'hp': 520, 'atk_min': 56, 'atk_max': 76, 'money_min': 200, 'money_max': 280, 'class': 'B(Mythical)', 'is_boss': False, 'is_super_boss': False, 'drop': {'potion': 0.2, 'phoenix_feather': 0.3, 'mythical_magic_pack': 0.25, 'fire_essence': 0.3, 'perm_exp_upgrade': 0.14, 'perm_strength_upgrade': 0.14, 'perm_defense_upgrade': 0.14, 'perm_health_upgrade': 0.14, 'perm_mana_upgrade': 0.14, 'perm_crit_chance_upgrade': 0.14, 'perm_mana_regen_upgrade': 0.14, 'perm_lifesteal_upgrade': 0.14, 'perm_lifesteal_chance_upgrade': 0.14}, 'weight': 2, 'area': 51, 'element': 'fire', 'exp_min': 75, 'exp_max': 189},
    {'name': 'Crystal Golem', 'hp': 640, 'atk_min': 48, 'atk_max': 68, 'money_min': 190, 'money_max': 260, 'class': 'B(Mythical)', 'is_boss': False, 'is_super_boss': False, 'drop': {'potion': 0.2, 'crystal_shard': 0.4, 'mythical_magic_pack': 0.2, 'stone_core': 0.3, 'perm_exp_upgrade': 0.14, 'perm_strength_upgrade': 0.14, 'perm_defense_upgrade': 0.14, 'perm_health_upgrade': 0.14, 'perm_mana_upgrade': 0.14, 'perm_crit_chance_upgrade': 0.14, 'perm_mana_regen_upgrade': 0.14, 'perm_lifesteal_upgrade': 0.14, 'perm_lifesteal_chance_upgrade': 0.14}, 'weight': 2, 'area': 53, 'element': 'nature', 'exp_min': 75, 'exp_max': 189},
    {'name': 'Storm Dragon', 'hp': 560, 'atk_min': 54, 'atk_max': 74, 'money_min': 210, 'money_max': 290, 'class': 'B(Mythical)', 'is_boss': False, 'is_super_boss': False, 'drop': {'potion': 0.2, 'thunder_core': 0.4, 'mythical_magic_pack': 0.25, 'dragon_scale': 0.2, 'perm_exp_upgrade': 0.14, 'perm_strength_upgrade': 0.14, 'perm_defense_upgrade': 0.14, 'perm_health_upgrade': 0.14, 'perm_mana_upgrade': 0.14, 'perm_crit_chance_upgrade': 0.14, 'perm_mana_regen_upgrade': 0.14, 'perm_lifesteal_upgrade': 0.14, 'perm_lifesteal_chance_upgrade': 0.14}, 'weight': 2, 'area': 55, 'element': 'lightning', 'exp_min': 75, 'exp_max': 189},
    
    # A(Prismatic) monsters - Areas 61-80
    {'name': 'Void Walker', 'hp': 720, 'atk_min': 64, 'atk_max': 84, 'money_min': 250, 'money_max': 350, 'class': 'A(Prismatic)', 'is_boss': False, 'is_super_boss': False, 'drop': {'potion': 0.15, 'void_fragment': 0.3, 'mythical_magic_pack': 0.2, 'prismatic_magic_pack': 0.1, 'perm_exp_upgrade': 0.16, 'perm_strength_upgrade': 0.16, 'perm_defense_upgrade': 0.16, 'perm_health_upgrade': 0.16, 'perm_mana_upgrade': 0.16, 'perm_crit_chance_upgrade': 0.16, 'perm_mana_regen_upgrade': 0.16, 'perm_lifesteal_upgrade': 0.16, 'perm_lifesteal_chance_upgrade': 0.16}, 'weight': 2, 'area': 61, 'element': 'mana', 'exp_min': 113, 'exp_max': 284},
    {'name': 'Celestial Guardian', 'hp': 800, 'atk_min': 60, 'atk_max': 80, 'money_min': 280, 'money_max': 380, 'class': 'A(Prismatic)', 'is_boss': False, 'is_super_boss': False, 'drop': {'potion': 0.2, 'holy_light': 0.3, 'mythical_magic_pack': 0.25, 'prismatic_magic_pack': 0.15, 'perm_exp_upgrade': 0.16, 'perm_strength_upgrade': 0.16, 'perm_defense_upgrade': 0.16, 'perm_health_upgrade': 0.16, 'perm_mana_upgrade': 0.16, 'perm_crit_chance_upgrade': 0.16, 'perm_mana_regen_upgrade': 0.16, 'perm_lifesteal_upgrade': 0.16, 'perm_lifesteal_chance_upgrade': 0.16}, 'weight': 2, 'area': 63, 'element': 'mana', 'exp_min': 113, 'exp_max': 284},
    {'name': 'Star Weaver', 'hp': 680, 'atk_min': 66, 'atk_max': 86, 'money_min': 260, 'money_max': 360, 'class': 'A(Prismatic)', 'is_boss': False, 'is_super_boss': False, 'drop': {'potion': 0.2, 'star_dust': 0.4, 'mythical_magic_pack': 0.2, 'prismatic_magic_pack': 0.1, 'perm_exp_upgrade': 0.16, 'perm_strength_upgrade': 0.16, 'perm_defense_upgrade': 0.16, 'perm_health_upgrade': 0.16, 'perm_mana_upgrade': 0.16, 'perm_crit_chance_upgrade': 0.16, 'perm_mana_regen_upgrade': 0.16, 'perm_lifesteal_upgrade': 0.16, 'perm_lifesteal_chance_upgrade': 0.16}, 'weight': 2, 'area': 65, 'element': 'mana', 'exp_min': 113, 'exp_max': 284},
    {'name': 'Moon Sentinel', 'hp': 760, 'atk_min': 62, 'atk_max': 82, 'money_min': 270, 'money_max': 370, 'class': 'A(Prismatic)', 'is_boss': False, 'is_super_boss': False, 'drop': {'potion': 0.2, 'moon_rock': 0.3, 'mythical_magic_pack': 0.2, 'prismatic_magic_pack': 0.15, 'perm_exp_upgrade': 0.16, 'perm_strength_upgrade': 0.16, 'perm_defense_upgrade': 0.16, 'perm_health_upgrade': 0.16, 'perm_mana_upgrade': 0.16, 'perm_crit_chance_upgrade': 0.16, 'perm_mana_regen_upgrade': 0.16, 'perm_lifesteal_upgrade': 0.16, 'perm_lifesteal_chance_upgrade': 0.16}, 'weight': 2, 'area': 67, 'element': 'mana', 'exp_min': 113, 'exp_max': 284},
    {'name': 'Sun Champion', 'hp': 880, 'atk_min': 72, 'atk_max': 92, 'money_min': 320, 'money_max': 420, 'class': 'A(Prismatic)', 'is_boss': False, 'is_super_boss': False, 'drop': {'potion': 0.2, 'sun_stone': 0.3, 'prismatic_magic_pack': 0.25, 'divine_magic_pack': 0.1, 'perm_exp_upgrade': 0.18, 'perm_strength_upgrade': 0.18, 'perm_defense_upgrade': 0.18, 'perm_health_upgrade': 0.18, 'perm_mana_upgrade': 0.18, 'perm_crit_chance_upgrade': 0.18, 'perm_mana_regen_upgrade': 0.18, 'perm_lifesteal_upgrade': 0.18, 'perm_lifesteal_chance_upgrade': 0.18}, 'weight': 1, 'area': 69, 'element': 'fire', 'exp_min': 170, 'exp_max': 427},
    {'name': 'Void Lord', 'hp': 960, 'atk_min': 76, 'atk_max': 96, 'money_min': 350, 'money_max': 450, 'class': 'A(Prismatic)', 'is_boss': False, 'is_super_boss': False, 'drop': {'potion': 0.2, 'void_fragment': 0.4, 'prismatic_magic_pack': 0.25, 'divine_magic_pack': 0.15, 'perm_exp_upgrade': 0.18, 'perm_strength_upgrade': 0.18, 'perm_defense_upgrade': 0.18, 'perm_health_upgrade': 0.18, 'perm_mana_upgrade': 0.18, 'perm_crit_chance_upgrade': 0.18, 'perm_mana_regen_upgrade': 0.18, 'perm_lifesteal_upgrade': 0.18, 'perm_lifesteal_chance_upgrade': 0.18}, 'weight': 1, 'area': 71, 'element': 'mana', 'exp_min': 170, 'exp_max': 427},
    {'name': 'Divine Paladin', 'hp': 840, 'atk_min': 74, 'atk_max': 94, 'money_min': 330, 'money_max': 430, 'class': 'A(Prismatic)', 'is_boss': False, 'is_super_boss': False, 'drop': {'potion': 0.2, 'holy_light': 0.4, 'prismatic_magic_pack': 0.3, 'divine_magic_pack': 0.15, 'perm_exp_upgrade': 0.18, 'perm_strength_upgrade': 0.18, 'perm_defense_upgrade': 0.18, 'perm_health_upgrade': 0.18, 'perm_mana_upgrade': 0.18, 'perm_crit_chance_upgrade': 0.18, 'perm_mana_regen_upgrade': 0.18, 'perm_lifesteal_upgrade': 0.18, 'perm_lifesteal_chance_upgrade': 0.18}, 'weight': 1, 'area': 73, 'element': 'mana', 'exp_min': 170, 'exp_max': 427},
    {'name': 'Cosmic Mage', 'hp': 920, 'atk_min': 70, 'atk_max': 90, 'money_min': 340, 'money_max': 440, 'class': 'A(Prismatic)', 'is_boss': False, 'is_super_boss': False, 'drop': {'potion': 0.2, 'star_dust': 0.3, 'prismatic_magic_pack': 0.25, 'divine_magic_pack': 0.2, 'perm_exp_upgrade': 0.18, 'perm_strength_upgrade': 0.18, 'perm_defense_upgrade': 0.18, 'perm_health_upgrade': 0.18, 'perm_mana_upgrade': 0.18, 'perm_crit_chance_upgrade': 0.18, 'perm_mana_regen_upgrade': 0.18, 'perm_lifesteal_upgrade': 0.18, 'perm_lifesteal_chance_upgrade': 0.18}, 'weight': 1, 'area': 75, 'element': 'mana', 'exp_min': 170, 'exp_max': 427},
    
    # S(Divine) monsters - Areas 81-99
    {'name': 'Eternal Dragon', 'hp': 1200, 'atk_min': 84, 'atk_max': 108, 'money_min': 450, 'money_max': 600, 'class': 'S(Divine)', 'is_boss': False, 'is_super_boss': False, 'drop': {'potion': 0.15, 'dragon_scale': 0.4, 'divine_magic_pack': 0.3, 'transcendent_magic_pack': 0.1, 'perm_exp_upgrade': 0.2, 'perm_strength_upgrade': 0.2, 'perm_defense_upgrade': 0.2, 'perm_health_upgrade': 0.2, 'perm_mana_upgrade': 0.2, 'perm_crit_chance_upgrade': 0.2, 'perm_mana_regen_upgrade': 0.2, 'perm_lifesteal_upgrade': 0.2, 'perm_lifesteal_chance_upgrade': 0.2}, 'weight': 1, 'area': 81, 'element': 'fire', 'exp_min': 256, 'exp_max': 640},
    {'name': 'Void Reaper', 'hp': 1120, 'atk_min': 90, 'atk_max': 114, 'money_min': 480, 'money_max': 630, 'class': 'S(Divine)', 'is_boss': False, 'is_super_boss': False, 'drop': {'potion': 0.2, 'void_fragment': 0.4, 'divine_magic_pack': 0.3, 'transcendent_magic_pack': 0.15, 'perm_exp_upgrade': 0.2, 'perm_strength_upgrade': 0.2, 'perm_defense_upgrade': 0.2, 'perm_health_upgrade': 0.2, 'perm_mana_upgrade': 0.2, 'perm_crit_chance_upgrade': 0.2, 'perm_mana_regen_upgrade': 0.2, 'perm_lifesteal_upgrade': 0.2, 'perm_lifesteal_chance_upgrade': 0.2}, 'weight': 1, 'area': 83, 'element': 'mana', 'exp_min': 256, 'exp_max': 640},
    {'name': 'Celestial Phoenix', 'hp': 1160, 'atk_min': 86, 'atk_max': 110, 'money_min': 470, 'money_max': 620, 'class': 'S(Divine)', 'is_boss': False, 'is_super_boss': False, 'drop': {'potion': 0.2, 'phoenix_feather': 0.4, 'divine_magic_pack': 0.35, 'transcendent_magic_pack': 0.15, 'perm_exp_upgrade': 0.2, 'perm_strength_upgrade': 0.2, 'perm_defense_upgrade': 0.2, 'perm_health_upgrade': 0.2, 'perm_mana_upgrade': 0.2, 'perm_crit_chance_upgrade': 0.2, 'perm_mana_regen_upgrade': 0.2, 'perm_lifesteal_upgrade': 0.2, 'perm_lifesteal_chance_upgrade': 0.2}, 'weight': 1, 'area': 85, 'element': 'fire', 'exp_min': 256, 'exp_max': 640},
    {'name': 'Cosmic Entity', 'hp': 1240, 'atk_min': 82, 'atk_max': 106, 'money_min': 460, 'money_max': 610, 'class': 'S(Divine)', 'is_boss': False, 'is_super_boss': False, 'drop': {'potion': 0.2, 'star_dust': 0.4, 'divine_magic_pack': 0.3, 'transcendent_magic_pack': 0.2, 'perm_exp_upgrade': 0.2, 'perm_strength_upgrade': 0.2, 'perm_defense_upgrade': 0.2, 'perm_health_upgrade': 0.2, 'perm_mana_upgrade': 0.2, 'perm_crit_chance_upgrade': 0.2, 'perm_mana_regen_upgrade': 0.2, 'perm_lifesteal_upgrade': 0.2, 'perm_lifesteal_chance_upgrade': 0.2}, 'weight': 1, 'area': 87, 'element': 'mana', 'exp_min': 256, 'exp_max': 640},
    {'name': 'Shadow Wraith', 'hp': 2000, 'atk_min': 120, 'atk_max': 160, 'money_min': 1000, 'money_max': 1500, 'class': 'S(Divine)', 'is_boss': False, 'is_super_boss': False, 'drop': {'potion': 1.0, 'strength_boost': 1.0, 'defense_boost': 1.0, 'crit_boost': 1.0, 'prismatic_magic_pack': 0.8, 'divine_magic_pack': 0.8, 'soul_shard': 1.0, 'perm_exp_upgrade': 1.0, 'perm_strength_upgrade': 1.0, 'perm_defense_upgrade': 1.0, 'perm_health_upgrade': 1.0, 'perm_mana_upgrade': 1.0, 'perm_crit_chance_upgrade': 1.0, 'perm_mana_regen_upgrade': 1.0, 'perm_lifesteal_upgrade': 1.0, 'perm_lifesteal_chance_upgrade': 1.0}, 'weight': 1, 'area': 89, 'element': 'mana', 'exp_min': 500, 'exp_max': 1000},
    {'name': 'Celestial Beast', 'hp': 2400, 'atk_min': 110, 'atk_max': 150, 'money_min': 1200, 'money_max': 1800, 'class': 'S(Divine)', 'is_boss': False, 'is_super_boss': False, 'drop': {'potion': 1.0, 'strength_boost': 1.0, 'defense_boost': 1.0, 'crit_boost': 1.0, 'prismatic_magic_pack': 0.8, 'divine_magic_pack': 0.8, 'soul_shard': 1.0, 'perm_exp_upgrade': 1.0, 'perm_strength_upgrade': 1.0, 'perm_defense_upgrade': 1.0, 'perm_health_upgrade': 1.0, 'perm_mana_upgrade': 1.0, 'perm_crit_chance_upgrade': 1.0, 'perm_mana_regen_upgrade': 1.0, 'perm_lifesteal_upgrade': 1.0, 'perm_lifesteal_chance_upgrade': 1.0}, 'weight': 1, 'area': 91, 'element': 'mana', 'exp_min': 600, 'exp_max': 1200},
    {'name': 'Void Walker II', 'hp': 2800, 'atk_min': 140, 'atk_max': 180, 'money_min': 1400, 'money_max': 2000, 'class': 'S(Divine)', 'is_boss': False, 'is_super_boss': False, 'drop': {'potion': 1.0, 'strength_boost': 1.0, 'defense_boost': 1.0, 'crit_boost': 1.0, 'prismatic_magic_pack': 0.8, 'divine_magic_pack': 0.8, 'soul_shard': 1.0, 'perm_exp_upgrade': 1.0, 'perm_strength_upgrade': 1.0, 'perm_defense_upgrade': 1.0, 'perm_health_upgrade': 1.0, 'perm_mana_upgrade': 1.0, 'perm_crit_chance_upgrade': 1.0, 'perm_mana_regen_upgrade': 1.0, 'perm_lifesteal_upgrade': 1.0, 'perm_lifesteal_chance_upgrade': 1.0}, 'weight': 1, 'area': 93, 'element': 'mana', 'exp_min': 700, 'exp_max': 1400},
    {'name': 'Dragon Hatchling', 'hp': 3200, 'atk_min': 130, 'atk_max': 170, 'money_min': 1600, 'money_max': 2300, 'class': 'S(Divine)', 'is_boss': False, 'is_super_boss': False, 'drop': {'potion': 1.0, 'strength_boost': 1.0, 'defense_boost': 1.0, 'crit_boost': 1.0, 'prismatic_magic_pack': 0.8, 'divine_magic_pack': 0.8, 'soul_shard': 1.0, 'perm_exp_upgrade': 1.0, 'perm_strength_upgrade': 1.0, 'perm_defense_upgrade': 1.0, 'perm_health_upgrade': 1.0, 'perm_mana_upgrade': 1.0, 'perm_crit_chance_upgrade': 1.0, 'perm_mana_regen_upgrade': 1.0, 'perm_lifesteal_upgrade': 1.0, 'perm_lifesteal_chance_upgrade': 1.0}, 'weight': 1, 'area': 95, 'element': 'fire', 'exp_min': 800, 'exp_max': 1600},
    {'name': 'Storm Elemental', 'hp': 3600, 'atk_min': 160, 'atk_max': 200, 'money_min': 1800, 'money_max': 2600, 'class': 'S(Divine)', 'is_boss': False, 'is_super_boss': False, 'drop': {'potion': 1.0, 'strength_boost': 1.0, 'defense_boost': 1.0, 'crit_boost': 1.0, 'prismatic_magic_pack': 0.8, 'divine_magic_pack': 0.8, 'soul_shard': 1.0, 'perm_exp_upgrade': 1.0, 'perm_strength_upgrade': 1.0, 'perm_defense_upgrade': 1.0, 'perm_health_upgrade': 1.0, 'perm_mana_upgrade': 1.0, 'perm_crit_chance_upgrade': 1.0, 'perm_mana_regen_upgrade': 1.0, 'perm_lifesteal_upgrade': 1.0, 'perm_lifesteal_chance_upgrade': 1.0}, 'weight': 1, 'area': 97, 'element': 'lightning', 'exp_min': 900, 'exp_max': 1800},
    {'name': 'Phoenix Chick', 'hp': 4000, 'atk_min': 150, 'atk_max': 190, 'money_min': 2000, 'money_max': 2900, 'class': 'S(Divine)', 'is_boss': False, 'is_super_boss': False, 'drop': {'potion': 1.0, 'strength_boost': 1.0, 'defense_boost': 1.0, 'crit_boost': 1.0, 'prismatic_magic_pack': 0.8, 'divine_magic_pack': 0.8, 'soul_shard': 1.0, 'perm_exp_upgrade': 1.0, 'perm_strength_upgrade': 1.0, 'perm_defense_upgrade': 1.0, 'perm_health_upgrade': 1.0, 'perm_mana_upgrade': 1.0, 'perm_crit_chance_upgrade': 1.0, 'perm_mana_regen_upgrade': 1.0, 'perm_lifesteal_upgrade': 1.0, 'perm_lifesteal_chance_upgrade': 1.0}, 'weight': 1, 'area': 99, 'element': 'fire', 'exp_min': 1000, 'exp_max': 2000},
    
    # SS(Transcendent) monsters - Areas 90-99
    {'name': 'Transcendent Being', 'hp': 1600, 'atk_min': 100, 'atk_max': 130, 'money_min': 600, 'money_max': 800, 'class': 'SS(Transcendent)', 'is_boss': False, 'is_super_boss': False, 'drop': {'potion': 0.2, 'transcendent_heart': 0.2, 'divine_magic_pack': 0.3, 'transcendent_magic_pack': 0.3, 'perm_exp_upgrade': 0.2, 'perm_strength_upgrade': 0.2, 'perm_defense_upgrade': 0.2, 'perm_health_upgrade': 0.2, 'perm_mana_upgrade': 0.2, 'perm_crit_chance_upgrade': 0.2, 'perm_mana_regen_upgrade': 0.2, 'perm_lifesteal_upgrade': 0.2, 'perm_lifesteal_chance_upgrade': 0.2}, 'weight': 1, 'area': 90, 'element': 'mana', 'exp_min': 384, 'exp_max': 961},
    {'name': 'Void Emperor', 'hp': 1680, 'atk_min': 104, 'atk_max': 134, 'money_min': 650, 'money_max': 850, 'class': 'SS(Transcendent)', 'is_boss': False, 'is_super_boss': False, 'drop': {'potion': 0.2, 'void_fragment': 0.4, 'divine_magic_pack': 0.3, 'transcendent_magic_pack': 0.35, 'perm_exp_upgrade': 0.2, 'perm_strength_upgrade': 0.2, 'perm_defense_upgrade': 0.2, 'perm_health_upgrade': 0.2, 'perm_mana_upgrade': 0.2, 'perm_crit_chance_upgrade': 0.2, 'perm_mana_regen_upgrade': 0.2, 'perm_lifesteal_upgrade': 0.2, 'perm_lifesteal_chance_upgrade': 0.2}, 'weight': 1, 'area': 92, 'element': 'mana', 'exp_min': 384, 'exp_max': 961},
    {'name': 'Divine Avatar', 'hp': 1640, 'atk_min': 102, 'atk_max': 132, 'money_min': 630, 'money_max': 830, 'class': 'SS(Transcendent)', 'is_boss': False, 'is_super_boss': False, 'drop': {'potion': 0.2, 'holy_light': 0.4, 'divine_magic_pack': 0.35, 'transcendent_magic_pack': 0.3, 'perm_exp_upgrade': 0.2, 'perm_strength_upgrade': 0.2, 'perm_defense_upgrade': 0.2, 'perm_health_upgrade': 0.2, 'perm_mana_upgrade': 0.2, 'perm_crit_chance_upgrade': 0.2, 'perm_mana_regen_upgrade': 0.2, 'perm_lifesteal_upgrade': 0.2, 'perm_lifesteal_chance_upgrade': 0.2}, 'weight': 1, 'area': 94, 'element': 'mana', 'exp_min': 384, 'exp_max': 961},
    {'name': 'Cosmic Overlord', 'hp': 1720, 'atk_min': 106, 'atk_max': 136, 'money_min': 670, 'money_max': 870, 'class': 'SS(Transcendent)', 'is_boss': False, 'is_super_boss': False, 'drop': {'potion': 0.2, 'star_dust': 0.4, 'divine_magic_pack': 0.3, 'transcendent_magic_pack': 0.4, 'perm_exp_upgrade': 0.2, 'perm_strength_upgrade': 0.2, 'perm_defense_upgrade': 0.2, 'perm_health_upgrade': 0.2, 'perm_mana_upgrade': 0.2, 'perm_crit_chance_upgrade': 0.2, 'perm_mana_regen_upgrade': 0.2, 'perm_lifesteal_upgrade': 0.2, 'perm_lifesteal_chance_upgrade': 0.2}, 'weight': 1, 'area': 96, 'element': 'mana', 'exp_min': 384, 'exp_max': 961},
    {'name': 'Void Emperor II', 'hp': 6400, 'atk_min': 220, 'atk_max': 260, 'money_min': 3200, 'money_max': 4700, 'class': 'SS(Transcendent)', 'is_boss': False, 'is_super_boss': False, 'drop': {'potion': 1.0, 'strength_boost': 1.0, 'defense_boost': 1.0, 'crit_boost': 1.0, 'divine_magic_pack': 0.8, 'transcendent_magic_pack': 0.8, 'soul_shard': 1.0, 'perm_exp_upgrade': 1.0, 'perm_strength_upgrade': 1.0, 'perm_defense_upgrade': 1.0, 'perm_health_upgrade': 1.0, 'perm_mana_upgrade': 1.0, 'perm_crit_chance_upgrade': 1.0, 'perm_mana_regen_upgrade': 1.0, 'perm_lifesteal_upgrade': 1.0, 'perm_lifesteal_chance_upgrade': 1.0}, 'weight': 1, 'area': 98, 'element': 'mana', 'exp_min': 1600, 'exp_max': 3200},
    {'name': 'Celestial Emperor II', 'hp': 6800, 'atk_min': 230, 'atk_max': 270, 'money_min': 3400, 'money_max': 5000, 'class': 'SS(Transcendent)', 'is_boss': False, 'is_super_boss': False, 'drop': {'potion': 1.0, 'strength_boost': 1.0, 'defense_boost': 1.0, 'crit_boost': 1.0, 'divine_magic_pack': 0.8, 'transcendent_magic_pack': 0.8, 'soul_shard': 1.0, 'perm_exp_upgrade': 1.0, 'perm_strength_upgrade': 1.0, 'perm_defense_upgrade': 1.0, 'perm_health_upgrade': 1.0, 'perm_mana_upgrade': 1.0, 'perm_crit_chance_upgrade': 1.0, 'perm_mana_regen_upgrade': 1.0, 'perm_lifesteal_upgrade': 1.0, 'perm_lifesteal_chance_upgrade': 1.0}, 'weight': 1, 'area': 99, 'element': 'mana', 'exp_min': 1700, 'exp_max': 3400},
    {'name': 'Dragon Overlord', 'hp': 7200, 'atk_min': 250, 'atk_max': 290, 'money_min': 3600, 'money_max': 5300, 'class': 'SS(Transcendent)', 'is_boss': False, 'is_super_boss': False, 'drop': {'potion': 1.0, 'strength_boost': 1.0, 'defense_boost': 1.0, 'crit_boost': 1.0, 'divine_magic_pack': 0.8, 'transcendent_magic_pack': 0.8, 'soul_shard': 1.0, 'perm_exp_upgrade': 1.0, 'perm_strength_upgrade': 1.0, 'perm_defense_upgrade': 1.0, 'perm_health_upgrade': 1.0, 'perm_mana_upgrade': 1.0, 'perm_crit_chance_upgrade': 1.0, 'perm_mana_regen_upgrade': 1.0, 'perm_lifesteal_upgrade': 1.0, 'perm_lifesteal_chance_upgrade': 1.0}, 'weight': 1, 'area': 99, 'element': 'fire', 'exp_min': 1800, 'exp_max': 3600},
    {'name': 'God of Chaos', 'hp': 8500, 'atk_min': 270, 'atk_max': 320, 'money_min': 4000, 'money_max': 6000, 'class': 'SS(Transcendent)', 'is_boss': True, 'is_super_boss': False, 'drop': {'potion': 1.0, 'strength_boost': 1.0, 'defense_boost': 1.0, 'crit_boost': 1.0, 'divine_magic_pack': 0.8, 'transcendent_magic_pack': 0.8, 'soul_shard': 1.0, 'perm_exp_upgrade': 1.0, 'perm_strength_upgrade': 1.0, 'perm_defense_upgrade': 1.0, 'perm_health_upgrade': 1.0, 'perm_mana_upgrade': 1.0, 'perm_crit_chance_upgrade': 1.0, 'perm_mana_regen_upgrade': 1.0, 'perm_lifesteal_upgrade': 1.0, 'perm_lifesteal_chance_upgrade': 1.0}, 'weight': 1, 'area': 99, 'element': 'mana', 'exp_min': 2000, 'exp_max': 4000},
    
    # Normal Boss monsters - Distributed across all areas
    {'name': 'Goblin King', 'hp': 100, 'atk_min': 15, 'atk_max': 25, 'money_min': 100, 'money_max': 200, 'class': 'D(Common)', 'is_boss': True, 'is_super_boss': False, 'drop': {'potion': 0.8, 'strength_boost': 0.3, 'defense_boost': 0.2, 'goblin_tooth': 0.8, 'common_magic_pack': 0.3, 'perm_exp_upgrade': 0.5, 'perm_strength_upgrade': 0.5, 'perm_defense_upgrade': 0.5, 'perm_health_upgrade': 0.5, 'perm_mana_upgrade': 0.5, 'perm_crit_chance_upgrade': 0.5, 'perm_mana_regen_upgrade': 0.5, 'perm_lifesteal_upgrade': 0.5, 'perm_lifesteal_chance_upgrade': 0.5}, 'weight': 0.5, 'area': 10, 'exp_min': 50, 'exp_max': 100},
    {'name': 'Wolf Alpha', 'hp': 150, 'atk_min': 20, 'atk_max': 30, 'money_min': 150, 'money_max': 250, 'class': 'D(Common)', 'is_boss': True, 'is_super_boss': False, 'drop': {'potion': 0.8, 'strength_boost': 0.3, 'defense_boost': 0.2, 'wolf_pelt': 0.8, 'common_magic_pack': 0.3, 'perm_exp_upgrade': 0.5, 'perm_strength_upgrade': 0.5, 'perm_defense_upgrade': 0.5, 'perm_health_upgrade': 0.5, 'perm_mana_upgrade': 0.5, 'perm_crit_chance_upgrade': 0.5, 'perm_mana_regen_upgrade': 0.5, 'perm_lifesteal_upgrade': 0.5, 'perm_lifesteal_chance_upgrade': 0.5}, 'weight': 0.5, 'area': 20, 'exp_min': 75, 'exp_max': 150},
    {'name': 'Dark Mage Lord', 'hp': 400, 'atk_min': 40, 'atk_max': 60, 'money_min': 300, 'money_max': 500, 'class': 'C(Rare)', 'is_boss': True, 'is_super_boss': False, 'drop': {'potion': 0.8, 'strength_boost': 0.4, 'defense_boost': 0.3, 'crit_boost': 0.2, 'rare_magic_pack': 0.5, 'dark_essence': 0.8, 'perm_exp_upgrade': 0.6, 'perm_strength_upgrade': 0.6, 'perm_defense_upgrade': 0.6, 'perm_health_upgrade': 0.6, 'perm_mana_upgrade': 0.6, 'perm_crit_chance_upgrade': 0.6, 'perm_mana_regen_upgrade': 0.6, 'perm_lifesteal_upgrade': 0.6, 'perm_lifesteal_chance_upgrade': 0.6}, 'weight': 0.5, 'area': 30, 'exp_min': 150, 'exp_max': 300},
    {'name': 'Troll King', 'hp': 800, 'atk_min': 60, 'atk_max': 90, 'money_min': 500, 'money_max': 800, 'class': 'C(Rare)', 'is_boss': True, 'is_super_boss': False, 'drop': {'potion': 0.8, 'strength_boost': 0.5, 'defense_boost': 0.4, 'regen_potion': 0.4, 'rare_magic_pack': 0.6, 'troll_core': 0.8, 'perm_exp_upgrade': 0.7, 'perm_strength_upgrade': 0.7, 'perm_defense_upgrade': 0.7, 'perm_health_upgrade': 0.7, 'perm_mana_upgrade': 0.7, 'perm_crit_chance_upgrade': 0.7, 'perm_mana_regen_upgrade': 0.7, 'perm_lifesteal_upgrade': 0.7, 'perm_lifesteal_chance_upgrade': 0.7}, 'weight': 0.5, 'area': 40, 'exp_min': 250, 'exp_max': 500},
    {'name': 'Shadow Assassin Master', 'hp': 1200, 'atk_min': 80, 'atk_max': 120, 'money_min': 800, 'money_max': 1200, 'class': 'B(Mythical)', 'is_boss': True, 'is_super_boss': False, 'drop': {'potion': 0.8, 'strength_boost': 0.6, 'defense_boost': 0.5, 'crit_boost': 0.4, 'mythical_magic_pack': 0.6, 'shadow_cloak': 0.8, 'perm_exp_upgrade': 0.8, 'perm_strength_upgrade': 0.8, 'perm_defense_upgrade': 0.8, 'perm_health_upgrade': 0.8, 'perm_mana_upgrade': 0.8, 'perm_crit_chance_upgrade': 0.8, 'perm_mana_regen_upgrade': 0.8, 'perm_lifesteal_upgrade': 0.8, 'perm_lifesteal_chance_upgrade': 0.8}, 'weight': 0.5, 'area': 50, 'exp_min': 400, 'exp_max': 800},
    {'name': 'Ice Queen', 'hp': 1800, 'atk_min': 100, 'atk_max': 150, 'money_min': 1200, 'money_max': 1800, 'class': 'B(Mythical)', 'is_boss': True, 'is_super_boss': False, 'drop': {'potion': 0.8, 'strength_boost': 0.6, 'defense_boost': 0.6, 'regen_potion': 0.5, 'mythical_magic_pack': 0.7, 'frozen_heart': 0.8, 'perm_exp_upgrade': 0.8, 'perm_strength_upgrade': 0.8, 'perm_defense_upgrade': 0.8, 'perm_health_upgrade': 0.8, 'perm_mana_upgrade': 0.8, 'perm_crit_chance_upgrade': 0.8, 'perm_mana_regen_upgrade': 0.8, 'perm_lifesteal_upgrade': 0.8, 'perm_lifesteal_chance_upgrade': 0.8}, 'weight': 0.5, 'area': 60, 'exp_min': 600, 'exp_max': 1200},
    {'name': 'Void Lord Prime', 'hp': 2400, 'atk_min': 150, 'atk_max': 200, 'money_min': 1800, 'money_max': 2500, 'class': 'A(Prismatic)', 'is_boss': True, 'is_super_boss': False, 'drop': {'potion': 0.8, 'strength_boost': 0.7, 'defense_boost': 0.6, 'crit_boost': 0.5, 'prismatic_magic_pack': 0.7, 'void_fragment': 0.8, 'perm_exp_upgrade': 0.9, 'perm_strength_upgrade': 0.9, 'perm_defense_upgrade': 0.9, 'perm_health_upgrade': 0.9, 'perm_mana_upgrade': 0.9, 'perm_crit_chance_upgrade': 0.9, 'perm_mana_regen_upgrade': 0.9, 'perm_lifesteal_upgrade': 0.9, 'perm_lifesteal_chance_upgrade': 0.9}, 'weight': 0.5, 'area': 70, 'exp_min': 900, 'exp_max': 1800},
    {'name': 'Celestial Emperor', 'hp': 3200, 'atk_min': 200, 'atk_max': 280, 'money_min': 2500, 'money_max': 3500, 'class': 'A(Prismatic)', 'is_boss': True, 'is_super_boss': False, 'drop': {'potion': 0.8, 'strength_boost': 0.8, 'defense_boost': 0.7, 'mana_upgrade_potion': 0.6, 'prismatic_magic_pack': 0.8, 'holy_light': 0.8, 'perm_exp_upgrade': 0.9, 'perm_strength_upgrade': 0.9, 'perm_defense_upgrade': 0.9, 'perm_health_upgrade': 0.9, 'perm_mana_upgrade': 0.9, 'perm_crit_chance_upgrade': 0.9, 'perm_mana_regen_upgrade': 0.9, 'perm_lifesteal_upgrade': 0.9, 'perm_lifesteal_chance_upgrade': 0.9}, 'weight': 0.5, 'area': 80, 'exp_min': 1200, 'exp_max': 2400},
    {'name': 'Eternal Dragon Lord', 'hp': 4800, 'atk_min': 300, 'atk_max': 400, 'money_min': 3500, 'money_max': 5000, 'class': 'S(Divine)', 'is_boss': True, 'is_super_boss': False, 'drop': {'potion': 0.8, 'strength_boost': 0.9, 'defense_boost': 0.8, 'crit_boost': 0.7, 'divine_magic_pack': 0.8, 'dragon_scale': 0.8, 'perm_exp_upgrade': 0.9, 'perm_strength_upgrade': 0.9, 'perm_defense_upgrade': 0.9, 'perm_health_upgrade': 0.9, 'perm_mana_upgrade': 0.9, 'perm_crit_chance_upgrade': 0.9, 'perm_mana_regen_upgrade': 0.9, 'perm_lifesteal_upgrade': 0.9, 'perm_lifesteal_chance_upgrade': 0.9}, 'weight': 0.5, 'area': 90, 'exp_min': 1800, 'exp_max': 3600},
    
    # Boss monsters - Area 100 (Original bosses with increased stats)
    {'name': 'Goblin King', 'hp': 400, 'atk_min': 100, 'atk_max': 200, 'money_min': 200, 'money_max': 400, 'class': 'D(Common)', 'is_boss': True, 'is_super_boss': False, 'drop': {'potion': 1.0, 'strength_boost': 0.5, 'defense_boost': 0.3, 'goblin_tooth': 1.0, 'common_magic_pack': 0.5, 'perm_exp_upgrade': 1.0, 'perm_strength_upgrade': 1.0, 'perm_defense_upgrade': 1.0, 'perm_health_upgrade': 1.0, 'perm_mana_upgrade': 1.0, 'perm_crit_chance_upgrade': 1.0, 'perm_mana_regen_upgrade': 1.0, 'perm_lifesteal_upgrade': 1.0, 'perm_lifesteal_chance_upgrade': 1.0}, 'weight': 1, 'area': 100, 'exp_min': 250, 'exp_max': 500},
    {'name': 'Skeleton King', 'hp': 1000, 'atk_min': 220, 'atk_max': 350, 'money_min': 750, 'money_max': 2000, 'class': 'B(Mythical)', 'is_boss': True, 'is_super_boss': False, 'drop': {'potion': 1.0, 'strength_boost': 0.8, 'defense_boost': 0.5, 'crit_boost': 0.4, 'rare_magic_pack': 0.8, 'mythical_magic_pack': 0.4, 'skeleton_bone': 1.0, 'perm_exp_upgrade': 1.0, 'perm_strength_upgrade': 1.0, 'perm_defense_upgrade': 1.0, 'perm_health_upgrade': 1.0, 'perm_mana_upgrade': 1.0, 'perm_crit_chance_upgrade': 1.0, 'perm_mana_regen_upgrade': 1.0, 'perm_lifesteal_upgrade': 1.0, 'perm_lifesteal_chance_upgrade': 1.0}, 'weight': 1, 'area': 100, 'exp_min': 250, 'exp_max': 500},
    {'name': 'Troll Chieftain', 'hp': 1600, 'atk_min': 240, 'atk_max': 300, 'money_min': 1500, 'money_max': 3000, 'class': 'C(Rare)', 'is_boss': True, 'is_super_boss': False, 'drop': {'potion': 1.0, 'strength_boost': 0.7, 'defense_boost': 0.6, 'regen_potion': 0.5, 'rare_magic_pack': 0.7, 'mythical_magic_pack': 0.3, 'troll_core': 1.0, 'perm_exp_upgrade': 1.0, 'perm_strength_upgrade': 1.0, 'perm_defense_upgrade': 1.0, 'perm_health_upgrade': 1.0, 'perm_mana_upgrade': 1.0, 'perm_crit_chance_upgrade': 1.0, 'perm_mana_regen_upgrade': 1.0, 'perm_lifesteal_upgrade': 1.0, 'perm_lifesteal_chance_upgrade': 1.0}, 'weight': 1, 'area': 100, 'exp_min': 562, 'exp_max': 1125},
    {'name': 'Dark Lord', 'hp': 2400, 'atk_min': 270, 'atk_max': 378, 'money_min': 2500, 'money_max': 5000, 'class': 'B(Mythical)', 'is_boss': True, 'is_super_boss': False, 'drop': {'potion': 1.0, 'strength_boost': 0.8, 'defense_boost': 0.6, 'crit_boost': 0.5, 'mythical_magic_pack': 0.8, 'prismatic_magic_pack': 0.4, 'dark_essence': 1.0, 'perm_exp_upgrade': 1.0, 'perm_strength_upgrade': 1.0, 'perm_defense_upgrade': 1.0, 'perm_health_upgrade': 1.0, 'perm_mana_upgrade': 1.0, 'perm_crit_chance_upgrade': 1.0, 'perm_mana_regen_upgrade': 1.0, 'perm_lifesteal_upgrade': 1.0, 'perm_lifesteal_chance_upgrade': 1.0}, 'weight': 1, 'area': 100, 'exp_min': 843, 'exp_max': 1687},
    {'name': 'Ice Queen', 'hp': 3000, 'atk_min': 300, 'atk_max': 400, 'money_min': 3500, 'money_max': 6000, 'class': 'B(Mythical)', 'is_boss': True, 'is_super_boss': False, 'drop': {'potion': 1.0, 'defense_boost': 0.8, 'regen_potion': 0.7, 'mythical_magic_pack': 0.7, 'prismatic_magic_pack': 0.5, 'frozen_heart': 1.0, 'perm_exp_upgrade': 1.0, 'perm_strength_upgrade': 1.0, 'perm_defense_upgrade': 1.0, 'perm_health_upgrade': 1.0, 'perm_mana_upgrade': 1.0, 'perm_crit_chance_upgrade': 1.0, 'perm_mana_regen_upgrade': 1.0, 'perm_lifesteal_upgrade': 1.0, 'perm_lifesteal_chance_upgrade': 1.0}, 'weight': 1, 'area': 100, 'exp_min': 1265, 'exp_max': 2531},
    {'name': 'Phoenix Lord', 'hp': 3600, 'atk_min': 200, 'atk_max': 300, 'money_min': 4500, 'money_max': 7500, 'class': 'A(Prismatic)', 'is_boss': True, 'is_super_boss': False, 'drop': {'potion': 1.0, 'strength_boost': 0.8, 'mana_upgrade_potion': 0.6, 'mythical_magic_pack': 0.8, 'prismatic_magic_pack': 0.6, 'phoenix_feather': 1.0, 'perm_exp_upgrade': 1.0, 'perm_strength_upgrade': 1.0, 'perm_defense_upgrade': 1.0, 'perm_health_upgrade': 1.0, 'perm_mana_upgrade': 1.0, 'perm_crit_chance_upgrade': 1.0, 'perm_mana_regen_upgrade': 1.0, 'perm_lifesteal_upgrade': 1.0, 'perm_lifesteal_chance_upgrade': 1.0}, 'weight': 1, 'area': 100, 'exp_min': 1898, 'exp_max': 3796},
    {'name': 'Void Master', 'hp': 4400, 'atk_min': 380, 'atk_max': 480, 'money_min': 6000, 'money_max': 10000, 'class': 'A(Prismatic)', 'is_boss': True, 'is_super_boss': False, 'drop': {'potion': 1.0, 'strength_boost': 0.9, 'defense_boost': 0.8, 'crit_boost': 0.7, 'prismatic_magic_pack': 0.8, 'divine_magic_pack': 0.4, 'void_fragment': 1.0, 'perm_exp_upgrade': 1.0, 'perm_strength_upgrade': 1.0, 'perm_defense_upgrade': 1.0, 'perm_health_upgrade': 1.0, 'perm_mana_upgrade': 1.0, 'perm_crit_chance_upgrade': 1.0, 'perm_mana_regen_upgrade': 1.0, 'perm_lifesteal_upgrade': 1.0, 'perm_lifesteal_chance_upgrade': 1.0}, 'weight': 1, 'area': 100, 'exp_min': 2847, 'exp_max': 5695},
    {'name': 'Celestial Emperor', 'hp': 5600, 'atk_min': 500, 'atk_max': 700, 'money_min': 8000, 'money_max': 13000, 'class': 'S(Divine)', 'is_boss': True, 'is_super_boss': False, 'drop': {'potion': 1.0, 'strength_boost': 0.9, 'defense_boost': 0.9, 'mana_upgrade_potion': 0.7, 'prismatic_magic_pack': 0.8, 'divine_magic_pack': 0.6, 'holy_light': 1.0, 'perm_exp_upgrade': 1.0, 'perm_strength_upgrade': 1.0, 'perm_defense_upgrade': 1.0, 'perm_health_upgrade': 1.0, 'perm_mana_upgrade': 1.0, 'perm_crit_chance_upgrade': 1.0, 'perm_mana_regen_upgrade': 1.0, 'perm_lifesteal_upgrade': 1.0, 'perm_lifesteal_chance_upgrade': 1.0}, 'weight': 1, 'area': 100, 'exp_min': 4271, 'exp_max': 8542},
    {'name': 'Dragon Lord', 'hp': 7000, 'atk_min': 500, 'atk_max': 700, 'money_min': 10000, 'money_max': 16000, 'class': 'S(Divine)', 'is_boss': True, 'is_super_boss': False, 'drop': {'potion': 1.0, 'strength_boost': 1.0, 'defense_boost': 0.9, 'crit_boost': 0.8, 'divine_magic_pack': 0.8, 'transcendent_magic_pack': 0.4, 'dragon_scale': 1.0, 'perm_exp_upgrade': 1.0, 'perm_strength_upgrade': 1.0, 'perm_defense_upgrade': 1.0, 'perm_health_upgrade': 1.0, 'perm_mana_upgrade': 1.0, 'perm_crit_chance_upgrade': 1.0, 'perm_mana_regen_upgrade': 1.0, 'perm_lifesteal_upgrade': 1.0, 'perm_lifesteal_chance_upgrade': 1.0}, 'weight': 1, 'area': 100, 'exp_min': 6407, 'exp_max': 12814},
    {'name': 'Grim Reaper', 'hp': 8800, 'atk_min': 600, 'atk_max': 1000, 'money_min': 12000, 'money_max': 20000, 'class': 'S(Divine)', 'is_boss': True, 'is_super_boss': False, 'drop': {'potion': 1.0, 'strength_boost': 1.0, 'defense_boost': 1.0, 'crit_boost': 1.0, 'prismatic_magic_pack': 0.8, 'divine_magic_pack': 0.8, 'soul_shard': 1.0, 'perm_exp_upgrade': 1.0, 'perm_strength_upgrade': 1.0, 'perm_defense_upgrade': 1.0, 'perm_health_upgrade': 1.0, 'perm_mana_upgrade': 1.0, 'perm_crit_chance_upgrade': 1.0, 'perm_mana_regen_upgrade': 1.0, 'perm_lifesteal_upgrade': 1.0, 'perm_lifesteal_chance_upgrade': 1.0}, 'weight': 1, 'area': 100, 'exp_min': 9615670, 'exp_max': 10926721},
    
    # Super Boss monsters - Area 100 (Stats remain as they are already extremely high)
    {'name': 'Demon King Muzan', 'hp': 136980000, 'atk_min': 40000, 'atk_max': 50000, 'money_min': 100000000, 'money_max': 50000000000, 'class': 'SS(Transcendent)', 'is_boss': True, 'is_super_boss': True, 'drop': {'potion': 1.0, 'strength_boost': 1, 'defense_boost': 1, 'crit_boost': 1, 'transcendent_heart': 0.5, 'divine_magic_pack': 0.8, 'transcendent_magic_pack': 0.4, 'demon_horn': 1.0, 'perm_exp_upgrade': 1.0, 'perm_strength_upgrade': 1.0, 'perm_defense_upgrade': 1.0, 'perm_health_upgrade': 1.0, 'perm_mana_upgrade': 1.0, 'perm_crit_chance_upgrade': 1.0, 'perm_mana_regen_upgrade': 1.0, 'perm_lifesteal_upgrade': 1.0, 'perm_lifesteal_chance_upgrade': 1.0}, 'weight': 0.01, 'area': 100, 'exp_min': 8000000000, 'exp_max': 10000000000},
    {'name': 'Abyssal Dragon', 'hp': 120000000, 'atk_min': 35000, 'atk_max': 45000, 'money_min': 50000000, 'money_max': 30000000000, 'class': 'SS(Transcendent)', 'is_boss': True, 'is_super_boss': True, 'drop': {'potion': 1.0, 'strength_boost': 1, 'defense_boost': 1, 'crit_boost': 1, 'transcendent_heart': 0.4, 'divine_magic_pack': 0.7, 'transcendent_magic_pack': 0.5, 'dragon_scale': 1.0, 'perm_exp_upgrade': 1.0, 'perm_strength_upgrade': 1.0, 'perm_defense_upgrade': 1.0, 'perm_health_upgrade': 1.0, 'perm_mana_upgrade': 1.0, 'perm_crit_chance_upgrade': 1.0, 'perm_mana_regen_upgrade': 1.0, 'perm_lifesteal_upgrade': 1.0, 'perm_lifesteal_chance_upgrade': 1.0}, 'weight': 0.01, 'area': 100, 'exp_min': 7000000000, 'exp_max': 9000000000},
    {'name': 'Void Emperor', 'hp': 125000000, 'atk_min': 36000, 'atk_max': 46000, 'money_min': 60000000, 'money_max': 35000000000, 'class': 'SS(Transcendent)', 'is_boss': True, 'is_super_boss': True, 'drop': {'potion': 1.0, 'strength_boost': 1, 'defense_boost': 1, 'crit_boost': 1, 'transcendent_heart': 0.45, 'divine_magic_pack': 0.75, 'transcendent_magic_pack': 0.45, 'void_core': 1.0, 'perm_exp_upgrade': 1.0, 'perm_strength_upgrade': 1.0, 'perm_defense_upgrade': 1.0, 'perm_health_upgrade': 1.0, 'perm_mana_upgrade': 1.0, 'perm_crit_chance_upgrade': 1.0, 'perm_mana_regen_upgrade': 1.0, 'perm_lifesteal_upgrade': 1.0, 'perm_lifesteal_chance_upgrade': 1.0}, 'weight': 0.01, 'area': 100, 'exp_min': 7500000000, 'exp_max': 9500000000},
    {'name': 'Celestial Phoenix', 'hp': 118000000, 'atk_min': 34000, 'atk_max': 44000, 'money_min': 55000000, 'money_max': 32000000000, 'class': 'SS(Transcendent)', 'is_boss': True, 'is_super_boss': True, 'drop': {'potion': 1.0, 'strength_boost': 1, 'defense_boost': 1, 'crit_boost': 1, 'transcendent_heart': 0.42, 'divine_magic_pack': 0.72, 'transcendent_magic_pack': 0.42, 'phoenix_feather': 1.0, 'perm_exp_upgrade': 1.0, 'perm_strength_upgrade': 1.0, 'perm_defense_upgrade': 1.0, 'perm_health_upgrade': 1.0, 'perm_mana_upgrade': 1.0, 'perm_crit_chance_upgrade': 1.0, 'perm_mana_regen_upgrade': 1.0, 'perm_lifesteal_upgrade': 1.0, 'perm_lifesteal_chance_upgrade': 1.0}, 'weight': 0.01, 'area': 100, 'exp_min': 7200000000, 'exp_max': 9200000000},
    {'name': 'Eternal Titan', 'hp': 130000000, 'atk_min': 37000, 'atk_max': 47000, 'money_min': 65000000, 'money_max': 40000000000, 'class': 'SS(Transcendent)', 'is_boss': True, 'is_super_boss': True, 'drop': {'potion': 1.0, 'strength_boost': 1, 'defense_boost': 1, 'crit_boost': 1, 'transcendent_heart': 0.48, 'divine_magic_pack': 0.78, 'transcendent_magic_pack': 0.48, 'titan_core': 1.0, 'perm_exp_upgrade': 1.0, 'perm_strength_upgrade': 1.0, 'perm_defense_upgrade': 1.0, 'perm_health_upgrade': 1.0, 'perm_mana_upgrade': 1.0, 'perm_crit_chance_upgrade': 1.0, 'perm_mana_regen_upgrade': 1.0, 'perm_lifesteal_upgrade': 1.0, 'perm_lifesteal_chance_upgrade': 1.0}, 'weight': 0.01, 'area': 100, 'exp_min': 7700000000, 'exp_max': 9700000000},
]
MONSTER_ALIASES = {
    'boss': {'gk': 'Goblin King', 'sk': 'Skeleton King', 'tc': 'Troll Chieftain', 'dl': 'Dark Lord', 'iq': 'Ice Queen', 'pl': 'Phoenix Lord', 'vm': 'Void Master', 'ce': 'Celestial Emperor', 'drl': 'Dragon Lord', 'gr': 'Grim Reaper', 'dkm': 'Demon King Muzan', 'ad': 'Abyssal Dragon', 'vesb': 'Void Emperor', 'cpsb': 'Celestial Phoenix', 'et': 'Eternal Titan'},
    'normal': {'sl': 'Slime', 'g': 'Goblin', 'w': 'Wolf', 'gs': 'Goblin Shaman', 'sf': 'Forest Sprite', 'skel': 'Skeleton', 'o': 'Orc', 'sp': 'Giant Spider', 'bt': 'Dark Bat', 'b': 'Bandit', 'ow': 'Orc Warrior', 'dm': 'Dark Mage', 'sg': 'Stone Golem', 't': 'Troll', 'ie': 'Ice Elemental', 'fe': 'Fire Elemental', 'tb': 'Thunder Bird', 'dk': 'Dark Knight', 'sa': 'Shadow Assassin', 'am': 'Arcane Mage', 'wl': 'Warlock', 'ig': 'Ice Giant', 'p': 'Phoenix', 'cg': 'Crystal Golem', 'sd': 'Storm Dragon', 'vw': 'Void Walker', 'cg2': 'Celestial Guardian', 'sw': 'Star Weaver', 'ms': 'Moon Sentinel', 'sc': 'Sun Champion', 'vl': 'Void Lord', 'dp': 'Divine Paladin', 'cm': 'Cosmic Mage', 'ed': 'Eternal Dragon', 'vr': 'Void Reaper', 'cp': 'Celestial Phoenix', 'ce2': 'Cosmic Entity', 'tb2': 'Transcendent Being', 've': 'Void Emperor', 'da': 'Divine Avatar', 'co': 'Cosmic Overlord', 'swr': 'Shadow Wraith', 'cb': 'Celestial Beast', 'vwii': 'Void Walker II', 'dh': 'Dragon Hatchling', 'se': 'Storm Elemental', 'pc': 'Phoenix Chick', 'af': 'Abyssal Fiend', 'tt': 'Thunder Titan', 'hp': 'Holy Paladin', 'cw': 'Cosmic Wanderer', 'ef': 'Eternal Flame', 'veii': 'Void Emperor II', 'cei': 'Celestial Emperor II', 'do': 'Dragon Overlord', 'goc': 'God of Chaos'}
    }
MAGIC_PACKS = {
    'common_magic_pack': {'name': 'Common Magic Pack', 'tier': 'D(Common)', 'spells': ['spark', 'ember', 'aqua_jet', 'gust', 'stone_toss', 'mana_bolt'], 'drop_count': (1, 2), 'description': 'Contains 1-2 common spells'},
    'rare_magic_pack': {'name': 'Rare Magic Pack', 'tier': 'C(Rare)', 'spells': ['spark', 'ember', 'aqua_jet', 'gust', 'stone_toss', 'mana_bolt', 'fireball', 'ice_spike', 'shadow_shot', 'thunder_strike', 'poison_mist', 'spark_chain'], 'drop_count': (1, 3), 'description': 'Contains 1-3 spells (common or rare)'},
    'mythical_magic_pack': {'name': 'Mythical Magic Pack', 'tier': 'B(Mythical)', 'spells': ['fireball', 'ice_spike', 'shadow_shot', 'thunder_strike', 'poison_mist', 'spark_chain', 'meteor', 'frost_nova', 'void_bolt', 'life_drain', 'earth_quake', 'glacial_prison'], 'drop_count': (2, 4), 'description': 'Contains 2-4 spells (rare or mythical)'},
    'prismatic_magic_pack': {'name': 'Prismatic Magic Pack', 'tier': 'A(Prismatic)', 'spells': ['meteor', 'frost_nova', 'void_bolt', 'life_drain', 'earth_quake', 'glacial_prison', 'prism_beam', 'lightning_storm', 'aether_blast', 'mirror_shield', 'prismatic_orb', 'prismatic_shard'], 'drop_count': (2, 4), 'description': 'Contains 2-4 spells (mythical or prismatic)'},
    'divine_magic_pack': {'name': 'Divine Magic Pack', 'tier': 'S(Divine)', 'spells': ['prism_beam', 'lightning_storm', 'aether_blast', 'mirror_shield', 'prismatic_orb', 'prismatic_shard', 'divine_wrath', 'holy_barrier', 'celestial_fall', 'purge', 'resurgence', 'spectral_bind'], 'drop_count': (3, 5), 'description': 'Contains 3-5 spells (prismatic or divine)'},
    'transcendent_magic_pack': {'name': 'Transcendent Magic Pack', 'tier': 'SS(Transcendent)', 'spells': ['divine_wrath', 'holy_barrier', 'celestial_fall', 'purge', 'resurgence', 'spectral_bind', 'transcendence', 'unmaking', 'voidstorm', 'eternal_echo', 'reality_rend'], 'drop_count': (3, 5), 'description': 'Contains 3-5 spells (divine or transcendent)'}
    }
SPELLS_BY_KEY = {
    'spark': {'name': 'Spark', 'class': 'D(Common)', 'type': 'lightning', 'mana': 4, 'power': 8, 'lvl': 1, 'desc': 'Small electric spark.'},
    'ember': {'name': 'Ember', 'class': 'D(Common)', 'type': 'fire', 'mana': 4, 'power': 9, 'lvl': 1, 'desc': 'Tiny firebolt.'},
    'aqua_jet': {'name': 'Aqua Jet', 'class': 'D(Common)', 'type': 'ice', 'mana': 5, 'power': 10, 'lvl': 2, 'desc': 'Jet of melted ice.'},
    'gust': {'name': 'Gust', 'class': 'D(Common)', 'type': 'wind', 'mana': 4, 'power': 7, 'lvl': 1, 'desc': 'Blows at enemy.'},
    'stone_toss': {'name': 'Stone Toss', 'class': 'D(Common)', 'type': 'nature', 'mana': 6, 'power': 12, 'lvl': 2, 'desc': 'Small rock hurled.'},
    'mana_bolt': {'name': 'Mana Bolt', 'class': 'D(Common)', 'type': 'mana', 'mana': 6, 'power': 14, 'lvl': 3, 'desc': 'Basic mana projectile.'},
    'spark_chain': {'name': 'Spark Chain', 'class': 'C(Rare)', 'type': 'lightning', 'mana': 22, 'power': 80, 'lvl': 15, 'desc': 'Chaining sparks.'},
    'fireball': {'name': 'Fireball', 'class': 'C(Rare)', 'type': 'fire', 'mana': 15, 'power': 40, 'lvl': 10, 'desc': 'Explosive orb.'},
    'ice_spike': {'name': 'Ice Spike', 'class': 'C(Rare)', 'type': 'ice', 'mana': 14, 'power': 36, 'lvl': 9, 'desc': 'Sharp ice.'},
    'shadow_shot': {'name': 'Shadow Shot', 'class': 'C(Rare)', 'type': 'mana', 'mana': 16, 'power': 45, 'lvl': 11, 'desc': 'Dark bolt.'},
    'thunder_strike': {'name': 'Thunder Strike', 'class': 'C(Rare)', 'type': 'lightning', 'mana': 18, 'power': 50, 'lvl': 12, 'desc': 'Powerful lightning.'},
    'poison_mist': {'name': 'Poison Mist', 'class': 'C(Rare)', 'type': 'wind', 'mana': 12, 'power': 30, 'lvl': 10, 'desc': 'Toxic cloud.'},
    'meteor': {'name': 'Meteor', 'class': 'B(Mythical)', 'type': 'nature', 'mana': 55, 'power': 220, 'lvl': 30, 'desc': 'Crushing meteor.'},
    'frost_nova': {'name': 'Frost Nova', 'class': 'B(Mythical)', 'type': 'ice', 'mana': 45, 'power': 160, 'lvl': 28, 'desc': 'Freezes area.'},
    'void_bolt': {'name': 'Void Bolt', 'class': 'B(Mythical)', 'type': 'mana', 'mana': 60, 'power': 250, 'lvl': 32, 'desc': 'Nullifying energy.'},
    'life_drain': {'name': 'Life Drain', 'class': 'B(Mythical)', 'type': 'mana', 'mana': 50, 'power': 150, 'lvl': 30, 'desc': 'Steal HP.'},
    'earth_quake': {'name': 'nature Quake', 'class': 'B(Mythical)', 'type': 'nature', 'mana': 48, 'power': 180, 'lvl': 31, 'desc': 'Shake the ground.'},
    'glacial_prison': {'name': 'Glacial Prison', 'class': 'B(Mythical)', 'type': 'ice', 'mana': 70, 'power': 300, 'lvl': 35, 'desc': 'Encase the enemy.'},
    'prism_beam': {'name': 'Prism Beam', 'class': 'A(Prismatic)', 'type': 'mana', 'mana': 120, 'power': 700, 'lvl': 50, 'desc': 'Shredding beam.'},
    'lightning_storm': {'name': 'Lightning Storm', 'class': 'A(Prismatic)', 'type': 'lightning', 'mana': 110, 'power': 650, 'lvl': 48, 'desc': 'Storm of lightning.'},
    'aether_blast': {'name': 'Aether Blast', 'class': 'A(Prismatic)', 'type': 'mana', 'mana': 100, 'power': 600, 'lvl': 46, 'desc': 'Pure aether.'},
    'mirror_shield': {'name': 'Mirror Shield', 'class': 'A(Prismatic)', 'type': 'mana', 'mana': 40, 'power': 0, 'lvl': 45, 'desc': 'Reflect attacks.'},
    'prismatic_orb': {'name': 'Prismatic Orb', 'class': 'A(Prismatic)', 'type': 'mana', 'mana': 90, 'power': 520, 'lvl': 47, 'desc': 'Orb of prismatic energy.'},
    'prismatic_shard': {'name': 'Prismatic Shard', 'class': 'A(Prismatic)', 'type': 'mana', 'mana': 95, 'power': 560, 'lvl': 52, 'desc': 'Shards of light.'},
    'divine_wrath': {'name': 'Divine Wrath', 'class': 'S(Divine)', 'type': 'mana', 'mana': 300, 'power': 2000, 'lvl': 75, 'desc': 'Wrath of the gods.'},
    'holy_barrier': {'name': 'Holy Barrier', 'class': 'S(Divine)', 'type': 'heal', 'mana': 120, 'power': 0, 'lvl': 70, 'desc': 'Major protection.'},
    'celestial_fall': {'name': 'Celestial Fall', 'class': 'S(Divine)', 'type': 'nature', 'mana': 250, 'power': 1500, 'lvl': 72, 'desc': 'Celestial impact.'},
    'purge': {'name': 'Purge', 'class': 'S(Divine)', 'type': '', 'mana': 100, 'power': 480, 'lvl': 68, 'desc': 'Remove curses.'},
    'resurgence': {'name': 'Resurgence', 'class': 'S(Divine)', 'type': 'heal', 'mana': 200, 'power': 0, 'lvl': 74, 'desc': 'Large heal.'},
    'spectral_bind': {'name': 'Spectral Bind', 'class': 'S(Divine)', 'type': 'mana', 'mana': 180, 'power': 820, 'lvl': 66, 'desc': 'Bind spirit.'},
    'transcendence': {'name': 'Transcendence', 'class': 'SS(Transcendent)', 'type': 'mana', 'mana': 900, 'power': 8000, 'lvl': 95, 'desc': 'Transcend reality.'},
    'unmaking': {'name': 'Unmaking', 'class': 'SS(Transcendent)', 'type': 'mana', 'mana': 800, 'power': 7000, 'lvl': 90, 'desc': 'Unmake existence.'},
    'voidstorm': {'name': 'Voidstorm', 'class': 'SS(Transcendent)', 'type': 'mana', 'mana': 850, 'power': 7500, 'lvl': 92, 'desc': 'Storm of void.'},
    'eternal_echo': {'name': 'Eternal Echo', 'class': 'SS(Transcendent)', 'type': 'mana', 'mana': 950, 'power': 8500, 'lvl': 96, 'desc': 'Echo through eternity.'},
    'reality_rend': {'name': 'Reality Rend', 'class': 'SS(Transcendent)', 'type': 'mana', 'mana': 1000, 'power': 9000, 'lvl': 98, 'desc': 'Tear reality apart.'}
    }
MAGIC_PACK_ALIASES = {
    'common': 'common_magic_pack', 'c': 'common_magic_pack', 'rare': 'rare_magic_pack', 'r': 'rare_magic_pack', 'mythical': 'mythical_magic_pack', 'm': 'mythical_magic_pack', 'prismatic': 'prismatic_magic_pack', 'p': 'prismatic_magic_pack', 'divine': 'divine_magic_pack', 'd': 'divine_magic_pack', 'transcendent': 'transcendent_magic_pack', 't': 'transcendent_magic_pack'}
ACHIEVEMENTS = {
    'first_monster': {'name': 'First Blood', 'title': 'Slayer', 'condition': lambda stats: stats.get('monsters_defeated', 0) >= 1, 'desc': 'Defeat 1 monster'},
    'hundred_monsters': {'name': 'Monster Hunter', 'title': 'Hunter', 'condition': lambda stats: stats.get('monsters_defeated', 0) >= 100, 'desc': 'Defeat 100 monsters'},
    'thousand_monsters': {'name': 'Monster Slayer', 'title': 'Slayer II', 'condition': lambda stats: stats.get('monsters_defeated', 0) >= 1000, 'desc': 'Defeat 1000 monsters'},
    'boss_defeats_10': {'name': 'Boss Hunter', 'title': 'Boss Slayer', 'condition': lambda stats: stats.get('bosses_defeated', 0) >= 10, 'desc': 'Defeat 10 bosses'},
    'boss_defeats_50': {'name': 'Boss Master', 'title': 'Boss Master', 'condition': lambda stats: stats.get('bosses_defeated', 0) >= 50, 'desc': 'Defeat 50 bosses'},
    'millionaire': {'name': 'Wealthy', 'title': 'Millionaire', 'condition': lambda stats: stats.get('total_money_earned', 0) >= 1000000, 'desc': 'Earn 1,000,000 total money'},
    'spell_master': {'name': 'Spellcaster', 'title': 'Arcane Master', 'condition': lambda stats: len(stats.get('learned_spells', [])) >= 10, 'desc': 'Learn 10 spells'},
    'crafting_expert': {'name': 'Craftsman', 'title': 'Artisan', 'condition': lambda stats: stats.get('items_crafted', 0) >= 50, 'desc': 'Craft 50 items'},
    'collector': {'name': 'Collector', 'title': 'Collector', 'condition': lambda stats: stats.get('materials_collected', 0) >= 500, 'desc': 'Collect 500 materials'},
    'survivor': {'name': 'Survivor', 'title': 'Immortal', 'condition': lambda stats: stats.get('times_died', 0) >= 100, 'desc': 'Die 100 times'},
    'perfectionist': {'name': 'Perfect Game', 'title': 'Perfect', 'condition': lambda stats: stats.get('monsters_defeated', 0) >= 1000 and stats.get('bosses_defeated', 0) >= 10 and (len(stats.get('learned_spells', [])) >= 5) and (stats.get('level', 1) >= 50), 'desc': 'Defeat 1000 monsters, 10 bosses, learn 5 spells, reach level 50'},
    'legendary': {'name': 'Legendary Adventurer', 'title': 'Legendary', 'condition': lambda stats: stats.get('monsters_defeated', 0) >= 5000 and stats.get('bosses_defeated', 0) >= 100 and (stats.get('level', 1) >= 80), 'desc': 'Defeat 5000 monsters, 100 bosses, reach level 80'},
    'godlike': {'name': 'God Among Men', 'title': 'Deity', 'condition': lambda stats: stats.get('monsters_defeated', 0) >= 10000 and stats.get('bosses_defeated', 0) >= 200 and (stats.get('level', 1) >= 100), 'desc': 'Defeat 10000 monsters, 200 bosses, reach level 100'},
    'treasure_hunter': {'name': 'Treasure Hunter', 'title': 'Treasure King', 'condition': lambda stats: stats.get('dungeon_treasure_collected', 0) >= 500000, 'desc': 'Collect 500,000 from dungeon treasure'},
    'lucky': {'name': 'Lucky', 'title': "Fortune's Favorite", 'condition': lambda stats: stats.get('critical_hits', 0) >= 1000, 'desc': 'Land 1000 critical hits'}
    }
TITLES = {
    'novice': {'name': 'Novice', 'rarity': 'common', 'atk_boost': 0, 'def_boost': 0, 'hp_boost': 0, 'mana_boost': 0, 'exp_boost': 0, 'material_discount_percent': 0, 'money_boost_percent': 0, 'material_boost_percent': 0, 'treasure_boost_percent': 0, 'crit_chance_percent': 0, 'death_penalty_percent': 0, 'hp_regen_percent': 0, 'atk_percent': 0, 'def_percent': 0, 'hp_percent': 0, 'mana_percent': 0, 'desc': 'A beginner adventurer'},
    'apprentice': {'name': 'Apprentice', 'rarity': 'common', 'atk_boost': 1, 'def_boost': 1, 'hp_boost': 5, 'mana_boost': 5, 'exp_boost': 0, 'material_discount_percent': 0, 'money_boost_percent': 0, 'material_boost_percent': 0, 'treasure_boost_percent': 0, 'crit_chance_percent': 0, 'death_penalty_percent': 0, 'hp_regen_percent': 0, 'atk_percent': 0, 'def_percent': 0, 'hp_percent': 0, 'mana_percent': 0, 'desc': 'Learning the ways of combat'},
    'warrior': {'name': 'Warrior', 'rarity': 'common', 'atk_boost': 2, 'def_boost': 2, 'hp_boost': 10, 'mana_boost': 0, 'exp_boost': 0, 'material_discount_percent': 0, 'money_boost_percent': 0, 'material_boost_percent': 0, 'treasure_boost_percent': 0, 'crit_chance_percent': 0, 'death_penalty_percent': 0, 'hp_regen_percent': 0, 'atk_percent': 0, 'def_percent': 0, 'hp_percent': 0, 'mana_percent': 0, 'desc': 'A skilled fighter'},
    'champion': {'name': 'Champion', 'rarity': 'rare', 'atk_boost': 3, 'def_boost': 3, 'hp_boost': 15, 'mana_boost': 10, 'exp_boost': 5, 'material_discount_percent': 0, 'money_boost_percent': 0, 'material_boost_percent': 0, 'treasure_boost_percent': 0, 'crit_chance_percent': 0, 'death_penalty_percent': 0, 'hp_regen_percent': 0, 'atk_percent': 0, 'def_percent': 0, 'hp_percent': 0, 'mana_percent': 0, 'desc': 'A true hero'},
    'legend': {'name': 'Legend', 'rarity': 'rare', 'atk_boost': 4, 'def_boost': 4, 'hp_boost': 20, 'mana_boost': 15, 'exp_boost': 10, 'material_discount_percent': 0, 'money_boost_percent': 0, 'material_boost_percent': 0, 'treasure_boost_percent': 0, 'crit_chance_percent': 0, 'death_penalty_percent': 0, 'hp_regen_percent': 0, 'atk_percent': 0, 'def_percent': 0, 'hp_percent': 0, 'mana_percent': 0, 'desc': 'Known throughout the lands'},
    'master': {'name': 'Master', 'rarity': 'rare', 'atk_boost': 5, 'def_boost': 5, 'hp_boost': 25, 'mana_boost': 20, 'exp_boost': 15, 'material_discount_percent': 0, 'money_boost_percent': 0, 'material_boost_percent': 0, 'treasure_boost_percent': 0, 'crit_chance_percent': 0, 'death_penalty_percent': 0, 'hp_regen_percent': 0, 'atk_percent': 0, 'def_percent': 0, 'hp_percent': 0, 'mana_percent': 0, 'desc': 'A master of their craft'},
    'grandmaster': {'name': 'Grandmaster', 'rarity': 'mythical', 'atk_boost': 6, 'def_boost': 6, 'hp_boost': 30, 'mana_boost': 25, 'exp_boost': 20, 'material_discount_percent': 0, 'money_boost_percent': 0, 'material_boost_percent': 0, 'treasure_boost_percent': 0, 'crit_chance_percent': 0, 'death_penalty_percent': 0, 'hp_regen_percent': 0, 'atk_percent': 0, 'def_percent': 0, 'hp_percent': 0, 'mana_percent': 0, 'desc': 'A supreme expert'},
    'slayer': {'name': 'Slayer', 'rarity': 'mythical', 'atk_boost': 7, 'def_boost': 7, 'hp_boost': 35, 'mana_boost': 30, 'exp_boost': 25, 'material_discount_percent': 0, 'money_boost_percent': 0, 'material_boost_percent': 0, 'treasure_boost_percent': 0, 'crit_chance_percent': 0, 'death_penalty_percent': 0, 'hp_regen_percent': 0, 'atk_percent': 10, 'def_percent': 5, 'hp_percent': 0, 'mana_percent': 0, 'desc': 'Monster slayer extraordinaire'},
    'hunter': {'name': 'Hunter', 'rarity': 'mythical', 'atk_boost': 8, 'def_boost': 8, 'hp_boost': 40, 'mana_boost': 35, 'exp_boost': 30, 'material_discount_percent': 0, 'money_boost_percent': 0, 'material_boost_percent': 0, 'treasure_boost_percent': 0, 'crit_chance_percent': 0, 'death_penalty_percent': 0, 'hp_regen_percent': 0, 'atk_percent': 20, 'def_percent': 10, 'hp_percent': 0, 'mana_percent': 0, 'desc': 'Master hunter'},
    'slayer_ii': {'name': 'Slayer II', 'rarity': 'prismatic', 'atk_boost': 9, 'def_boost': 9, 'hp_boost': 45, 'mana_boost': 40, 'exp_boost': 35, 'material_discount_percent': 0, 'money_boost_percent': 0, 'material_boost_percent': 0, 'treasure_boost_percent': 0, 'crit_chance_percent': 0, 'death_penalty_percent': 0, 'hp_regen_percent': 0, 'atk_percent': 25, 'def_percent': 15, 'hp_percent': 0, 'mana_percent': 0, 'desc': 'Legendary monster slayer'},
    'boss_slayer': {'name': 'Boss Slayer', 'rarity': 'prismatic', 'atk_boost': 10, 'def_boost': 10, 'hp_boost': 50, 'mana_boost': 45, 'exp_boost': 40, 'material_discount_percent': 0, 'money_boost_percent': 0, 'material_boost_percent': 0, 'treasure_boost_percent': 0, 'crit_chance_percent': 0, 'death_penalty_percent': 0, 'hp_regen_percent': 0, 'atk_percent': 30, 'def_percent': 20, 'hp_percent': 0, 'mana_percent': 0, 'desc': 'Boss defeating champion'},
    'boss_master': {'name': 'Boss Master', 'rarity': 'prismatic', 'atk_boost': 11, 'def_boost': 11, 'hp_boost': 55, 'mana_boost': 50, 'exp_boost': 45, 'material_discount_percent': 0, 'money_boost_percent': 0, 'material_boost_percent': 0, 'treasure_boost_percent': 0, 'crit_chance_percent': 0, 'death_penalty_percent': 0, 'hp_regen_percent': 0, 'atk_percent': 35, 'def_percent': 25, 'hp_percent': 0, 'mana_percent': 0, 'desc': 'Master of bosses'},
    'millionaire': {'name': 'Millionaire', 'rarity': 'divine', 'atk_boost': 12, 'def_boost': 12, 'hp_boost': 60, 'mana_boost': 55, 'exp_boost': 50, 'material_discount_percent': 0, 'money_boost_percent': 20, 'material_boost_percent': 0, 'treasure_boost_percent': 0, 'crit_chance_percent': 0, 'death_penalty_percent': 0, 'hp_regen_percent': 0, 'atk_percent': 0, 'def_percent': 0, 'hp_percent': 0, 'mana_percent': 0, 'desc': 'Extremely wealthy'},
    'arcane_master': {'name': 'Arcane Master', 'rarity': 'divine', 'atk_boost': 13, 'def_boost': 13, 'hp_boost': 65, 'mana_boost': 60, 'exp_boost': 55, 'material_discount_percent': 0, 'money_boost_percent': 0, 'material_boost_percent': 0, 'treasure_boost_percent': 0, 'crit_chance_percent': 10, 'death_penalty_percent': 0, 'hp_regen_percent': 0, 'atk_percent': 0, 'def_percent': 0, 'hp_percent': 0, 'mana_percent': 20, 'desc': 'Master of magic'},
    'artisan': {'name': 'Artisan', 'rarity': 'divine', 'atk_boost': 14, 'def_boost': 14, 'hp_boost': 70, 'mana_boost': 65, 'exp_boost': 60, 'material_discount_percent': 20, 'money_boost_percent': 0, 'material_boost_percent': 0, 'treasure_boost_percent': 0, 'crit_chance_percent': 0, 'death_penalty_percent': 0, 'hp_regen_percent': 0, 'atk_percent': 0, 'def_percent': 0, 'hp_percent': 0, 'mana_percent': 0, 'desc': 'Master craftsman'},
    'collector': {'name': 'Collector', 'rarity': 'transcendent', 'atk_boost': 15, 'def_boost': 15, 'hp_boost': 75, 'mana_boost': 70, 'exp_boost': 65, 'material_discount_percent': 0, 'money_boost_percent': 0, 'material_boost_percent': 20, 'treasure_boost_percent': 0, 'crit_chance_percent': 0, 'death_penalty_percent': 0, 'hp_regen_percent': 0, 'atk_percent': 0, 'def_percent': 0, 'hp_percent': 0, 'mana_percent': 0, 'desc': 'Ultimate collector'},
    'immortal': {'name': 'Immortal', 'rarity': 'transcendent', 'atk_boost': 16, 'def_boost': 16, 'hp_boost': 80, 'mana_boost': 75, 'exp_boost': 70, 'material_discount_percent': 0, 'money_boost_percent': 0, 'material_boost_percent': 0, 'treasure_boost_percent': 0, 'crit_chance_percent': 0, 'death_penalty_percent': -30, 'hp_regen_percent': 0, 'atk_percent': 0, 'def_percent': 0, 'hp_percent': 0, 'mana_percent': 0, 'desc': 'Has cheated death many times'},
    'perfect': {'name': 'Perfect', 'rarity': 'transcendent', 'atk_boost': 17, 'def_boost': 17, 'hp_boost': 85, 'mana_boost': 80, 'exp_boost': 75, 'material_discount_percent': 0, 'money_boost_percent': 0, 'material_boost_percent': 0, 'treasure_boost_percent': 0, 'crit_chance_percent': 0, 'death_penalty_percent': 0, 'hp_regen_percent': 0, 'atk_percent': 10, 'def_percent': 10, 'hp_percent': 20, 'mana_percent': 20, 'desc': 'Achieved perfection'},
    'legendary': {'name': 'Legendary', 'rarity': 'transcendent', 'atk_boost': 18, 'def_boost': 18, 'hp_boost': 90, 'mana_boost': 85, 'exp_boost': 80, 'material_discount_percent': 0, 'money_boost_percent': 0, 'material_boost_percent': 0, 'treasure_boost_percent': 0, 'crit_chance_percent': 0, 'death_penalty_percent': 0, 'hp_regen_percent': 0, 'atk_percent': 30, 'def_percent': 30, 'hp_percent': 20, 'mana_percent': 0, 'desc': 'A living legend'},
    'deity': {'name': 'Deity', 'rarity': 'transcendent', 'atk_boost': 19, 'def_boost': 19, 'hp_boost': 95, 'mana_boost': 90, 'exp_boost': 85, 'material_discount_percent': 0, 'money_boost_percent': 0, 'material_boost_percent': 0, 'treasure_boost_percent': 0, 'crit_chance_percent': 0, 'death_penalty_percent': 0, 'hp_regen_percent': 0, 'atk_percent': 40, 'def_percent': 40, 'hp_percent': 30, 'mana_percent': 30, 'desc': 'God among men'},
    'treasure_king': {'name': 'Treasure King', 'rarity': 'transcendent', 'atk_boost': 20, 'def_boost': 20, 'hp_boost': 100, 'mana_boost': 95, 'exp_boost': 90, 'material_discount_percent': 0, 'money_boost_percent': 0, 'material_boost_percent': 0, 'treasure_boost_percent': 20, 'crit_chance_percent': 0, 'death_penalty_percent': 0, 'hp_regen_percent': 0, 'atk_percent': 0, 'def_percent': 0, 'hp_percent': 0, 'mana_percent': 0, 'desc': 'Master of treasures'},
    'fortunes_favorite': {'name': "Fortune's Favorite", 'rarity': 'transcendent', 'atk_boost': 21, 'def_boost': 21, 'hp_boost': 105, 'mana_boost': 100, 'exp_boost': 95, 'material_discount_percent': 0, 'money_boost_percent': 0, 'material_boost_percent': 0, 'treasure_boost_percent': 0, 'crit_chance_percent': 20, 'death_penalty_percent': 0, 'hp_regen_percent': 0, 'atk_percent': 0, 'def_percent': 0, 'hp_percent': 0, 'mana_percent': 0, 'desc': 'Always lucky'},
    'mytic': {'name': 'Mythic', 'rarity': 'mythical', 'atk_boost': 8, 'def_boost': 8, 'hp_boost': 40, 'mana_boost': 35, 'exp_boost': 30, 'material_discount_percent': 0, 'money_boost_percent': 0, 'material_boost_percent': 0, 'treasure_boost_percent': 0, 'crit_chance_percent': 0, 'death_penalty_percent': 0, 'hp_regen_percent': 0, 'atk_percent': 0, 'def_percent': 0, 'hp_percent': 0, 'mana_percent': 0, 'desc': 'Mythical being'},
    'transcendent': {'name': 'Transcendent', 'rarity': 'transcendent', 'atk_boost': 15, 'def_boost': 15, 'hp_boost': 75, 'mana_boost': 70, 'exp_boost': 65, 'material_discount_percent': 0, 'money_boost_percent': 0, 'material_boost_percent': 0, 'treasure_boost_percent': 0, 'crit_chance_percent': 0, 'death_penalty_percent': 0, 'hp_regen_percent': 0, 'atk_percent': 0, 'def_percent': 0, 'hp_percent': 0, 'mana_percent': 0, 'desc': 'Beyond mortal limits'},
    'godlike': {'name': 'Godlike', 'rarity': 'transcendent', 'atk_boost': 22, 'def_boost': 22, 'hp_boost': 110, 'mana_boost': 105, 'exp_boost': 100, 'material_discount_percent': 0, 'money_boost_percent': 0, 'material_boost_percent': 0, 'treasure_boost_percent': 0, 'crit_chance_percent': 0, 'death_penalty_percent': 0, 'hp_regen_percent': 0, 'atk_percent': 0, 'def_percent': 0, 'hp_percent': 0, 'mana_percent': 0, 'desc': 'A god among mortals'}
    }
RECIPES = {
    'potion': {'materials': {'slime_gel': 1, 'goblin_tooth': 1}, 'result': 'potion', 'qty': 1},
    'strong_potion': {'materials': {'slime_gel': 2, 'wolf_pelt': 1}, 'result': 'strong_potion', 'qty': 1},
    'ultra_potion': {'materials': {'slime_gel': 3, 'skeleton_bone': 2}, 'result': 'ultra_potion', 'qty': 1},
    'mana_upgrade_potion': {'materials': {'orc_iron': 2, 'bandit_cloth': 1}, 'result': 'mana_upgrade_potion', 'qty': 1},
    'perm_strength_upgrade': {'materials': {'troll_core': 5, 'dragon_scale': 1}, 'result': 'perm_strength_upgrade', 'qty': 1},
    'perm_defense_upgrade': {'materials': {'stone_core': 5, 'frozen_heart': 1}, 'result': 'perm_defense_upgrade', 'qty': 1},
    'perm_health_upgrade': {'materials': {'phoenix_feather': 3, 'holy_light': 2}, 'result': 'perm_health_upgrade', 'qty': 1},
    'perm_mana_upgrade': {'materials': {'demon_horn': 3, 'star_dust': 2}, 'result': 'perm_mana_upgrade', 'qty': 1},
    'perm_crit_chance_upgrade': {'materials': {'thunder_core': 5, 'lightning_feather': 3}, 'result': 'perm_crit_chance_upgrade', 'qty': 1},
    'perm_mana_regen_upgrade': {'materials': {'fire_essence': 4, 'ice_shard': 2}, 'result': 'perm_mana_regen_upgrade', 'qty': 1},
    'perm_lifesteal_upgrade': {'materials': {'demon_horn': 4, 'soul_shard': 2}, 'result': 'perm_lifesteal_upgrade', 'qty': 1},
    'perm_lifesteal_chance_upgrade': {'materials': {'void_fragment': 3, 'shadow_cloak': 1}, 'result': 'perm_lifesteal_chance_upgrade', 'qty': 1},
    'perm_magic_def_upgrade': {'materials': {'crystal_shard': 5, 'holy_light': 3}, 'result': 'perm_magic_def_upgrade', 'qty': 1},
    'perm_exp_upgrade': {'materials': {'moon_rock': 4, 'sun_stone': 2}, 'result': 'perm_exp_upgrade', 'qty': 1}
    }
WEAPONS = {
    'wooden_sword': {'name': 'Wooden Sword', 'atk': 2, 'price': 50, 'score_price': 0},
    'iron_sword': {'name': 'Iron Sword', 'atk': 5, 'price': 150, 'score_price': 0},
    'steel_sword': {'name': 'Steel Sword', 'atk': 8, 'price': 300, 'score_price': 0},
    'diamond_sword': {'name': 'Diamond Sword', 'atk': 50, 'price': 2000, 'score_price': 0},
    'void_sword': {'name': 'Void Sword', 'atk': 200, 'price': 8000, 'score_price': 0},
    'infinitium_sword': {'name': 'Infinitium Sword', 'atk': 2000, 'price': 800000, 'score_price': 25000},
    'frostblade': {'name': 'Frostblade', 'atk': 120, 'price': 5000, 'score_price': 200},
    'flameblade': {'name': 'Flameblade', 'atk': 130, 'price': 5500, 'score_price': 250},
    'thunder_sword': {'name': 'Thunder Sword', 'atk': 150, 'price': 7000, 'score_price': 400},
    'holy_avenger': {'name': 'Holy Avenger', 'atk': 180, 'price': 7500, 'score_price': 800},
    'dragon_slayer': {'name': 'Dragon Slayer', 'atk': 250, 'price': 15000, 'score_price': 1500},
    'cosmic_blade': {'name': 'Cosmic Blade', 'atk': 500, 'price': 30000, 'score_price': 3000},
    'transcendent_edge': {'name': 'Transcendent Edge', 'atk': 1500, 'price': 500000, 'score_price': 10000}
    }
ARMORS = {
    'leather_armor': {'name': 'Leather Armor', 'def': 1, 'price': 50},
    'chainmail': {'name': 'Chainmail', 'def': 3, 'price': 150},
    'plate_armor': {'name': 'Plate Armor', 'def': 6, 'price': 300},
    'diamond_armor': {'name': 'Diamond Armor', 'def': 25, 'price': 2000},
    'void_armor': {'name': 'Void Armor', 'def': 75, 'price': 8000},
    'infinitium_armor': {'name': 'Infinitium Armor', 'def': 300, 'price': 800000, 'score_price': 2500},
    'frost_armor': {'name': 'Frost Armor', 'def': 40, 'price': 4000, 'score_price': 150},
    'flame_armor': {'name': 'Flame Armor', 'def': 45, 'price': 4500, 'score_price': 200},
    'thunder_armor': {'name': 'Thunder Armor', 'def': 55, 'price': 6000, 'score_price': 350},
    'holy_armor': {'name': 'Holy Armor', 'def': 70, 'price': 9000, 'score_price': 700},
    'dragon_scale_armor': {'name': 'Dragon Scale Armor', 'def': 100, 'price': 14000, 'score_price': 1400},
    'cosmic_armor': {'name': 'Cosmic Armor', 'def': 200, 'price': 280000, 'score_price': 2800},
    'transcendent_armor': {'name': 'Transcendent Armor', 'def': 500, 'price': 950000, 'score_price': 9500}
    }
WANDS = {
    'apprentice_wand': {'name': 'Apprentice Wand', 'magic_atk': 5, 'price': 120},
    'mage_wand': {'name': 'Mage Wand', 'magic_atk': 20, 'price': 800},
    'archmage_staff': {'name': 'Archmage Staff', 'magic_atk': 120, 'price': 12000, 'score_price': 200},
    'frost_wand': {'name': 'Frost Wand', 'magic_atk': 60, 'price': 4000, 'score_price': 150},
    'flame_wand': {'name': 'Flame Wand', 'magic_atk': 65, 'price': 4500, 'score_price': 200},
    'thunder_wand': {'name': 'Thunder Wand', 'magic_atk': 75, 'price': 6000, 'score_price': 350},
    'holy_scepter': {'name': 'Holy Scepter', 'magic_atk': 90, 'price': 9000, 'score_price': 700},
    'dragon_staff': {'name': 'Dragon Staff', 'magic_atk': 125, 'price': 14000, 'score_price': 1400},
    'cosmic_scepter': {'name': 'Cosmic Scepter', 'magic_atk': 250, 'price': 28000, 'score_price': 2800},
    'transcendent_staff': {'name': 'Transcendent Staff', 'magic_atk': 750, 'price': 95000, 'score_price': 9500}
    }
ROBES = {
    'cloth_robe': {'name': 'Cloth Robe', 'magic_def': 2, 'price': 100},
    'silk_robe': {'name': 'Silk Robe', 'magic_def': 10, 'price': 900},
    'void_robe': {'name': 'Void Robe', 'magic_def': 80, 'price': 20000, 'score_price': 500},
    'frost_robe': {'name': 'Frost Robe', 'magic_def': 30, 'price': 4000, 'score_price': 150},
    'flame_robe': {'name': 'Flame Robe', 'magic_def': 35, 'price': 4500, 'score_price': 200},
    'thunder_robe': {'name': 'Thunder Robe', 'magic_def': 45, 'price': 6000, 'score_price': 350},
    'holy_robe': {'name': 'Holy Robe', 'magic_def': 60, 'price': 9000, 'score_price': 700},
    'dragon_robe': {'name': 'Dragon Robe', 'magic_def': 90, 'price': 14000, 'score_price': 1400},
    'cosmic_robe': {'name': 'Cosmic Robe', 'magic_def': 180, 'price': 28000, 'score_price': 2800},
    'transcendent_robe': {'name': 'Transcendent Robe', 'magic_def': 450, 'price': 95000, 'score_price': 9500}
    }
NECKLACES = {
    'health_amulet': {'name': 'Health Amulet', 'hp_bonus': 20, 'price': 500},
    'mana_amulet': {'name': 'Mana Amulet', 'mana_bonus': 15, 'price': 600},
    'strength_amulet': {'name': 'Strength Amulet', 'atk_bonus': 5, 'price': 700},
    'defense_amulet': {'name': 'Defense Amulet', 'def_bonus': 3, 'price': 650},
    'crit_amulet': {'name': 'Critical Amulet', 'crit_bonus': 10, 'price': 800},
    'lifesteal_amulet': {'name': 'Lifesteal Amulet', 'lifesteal_bonus': 5, 'price': 900},
    'frost_necklace': {'name': 'Frost Necklace', 'magic_def_bonus': 15, 'hp_bonus': 30, 'price': 3000, 'score_price': 100},
    'flame_necklace': {'name': 'Flame Necklace', 'magic_atk_bonus': 10, 'atk_bonus': 8, 'price': 3500, 'score_price': 150},
    'thunder_necklace': {'name': 'Thunder Necklace', 'crit_bonus': 15, 'atk_bonus': 10, 'price': 5000, 'score_price': 300},
    'holy_pendant': {'name': 'Holy Pendant', 'hp_bonus': 50, 'mana_bonus': 30, 'def_bonus': 5, 'price': 8000, 'score_price': 600},
    'dragon_necklace': {'name': 'Dragon Necklace', 'atk_bonus': 20, 'def_bonus': 15, 'hp_bonus': 70, 'price': 12000, 'score_price': 1200},
    'cosmic_necklace': {'name': 'Cosmic Necklace', 'magic_atk_bonus': 30, 'magic_def_bonus': 25, 'mana_bonus': 50, 'price': 24000, 'score_price': 2400},
    'transcendent_necklace': {'name': 'Transcendent Necklace', 'atk_bonus': 50, 'def_bonus': 40, 'hp_bonus': 150, 'mana_bonus': 100, 'crit_bonus': 20, 'lifesteal_bonus': 10, 'price': 800000, 'score_price': 8000}
    }
PERM_UPGRADES = {
    'perm_strength_upgrade': {'name': 'Perm Strength Upgrade', 'atk_increase': 10},
    'perm_defense_upgrade': {'name': 'Perm Defense Upgrade', 'def_increase': 5},
    'perm_health_upgrade': {'name': 'Perm Health Upgrade', 'hp_increase': 10},
    'perm_mana_upgrade': {'name': 'Perm Mana Upgrade', 'magic_increase': 20},
    'perm_crit_chance_upgrade': {'name': 'Perm Crit Chance Upgrade', 'crit_chance_increase': 5},
    'perm_mana_regen_upgrade': {'name': 'Perm Mana Regen Upgrade', 'mana_regen_increase': 5},
    'perm_magic_def_upgrade': {'name': 'Perm Magic Defense Upgrade', 'magic_def_increase': 5},
    'perm_lifesteal_upgrade': {'name': 'Perm Lifesteal Upgrade', 'max_lifesteal_increase': 10},
    'perm_lifesteal_chance_upgrade': {'name': 'Perm Lifesteal Chance Upgrade', 'lifesteal_chance_increase': 5},
    'perm_exp_upgrade': {'name': 'Perm Exp Upgrade', 'exp_increase': 10}
    }
POTIONS = {
    'potion': {'name': 'Potion', 'effect': 'heal', 'amount': 30},
    'strong_potion': {'name': 'Strong Potion', 'effect': 'heal', 'amount': 80},
    'ultra_potion': {'name': 'Ultra Potion', 'effect': 'heal', 'amount': 200},
    'strength_boost': {'name': 'Strength Boost', 'effect': 'buff_atk', 'amount': 5, 'duration': 4},
    'defense_boost': {'name': 'Defense Boost', 'effect': 'buff_def', 'amount': 3, 'duration': 4},
    'regen_potion': {'name': 'Regen Potion', 'effect': 'buff_hp_regen', 'amount': 12, 'duration': 4},
    'crit_boost': {'name': 'Crit Boost', 'effect': 'buff_crit', 'amount': 50, 'duration': 4},
    'mana_regen_potion': {'name': 'Mana Regen Potion', 'effect': 'buff_mana_regen', 'amount': 15, 'duration': 4},
    'instant_mana': {'name': 'Instant Mana', 'effect': 'full_mana'},
    'mana_upgrade_potion': {'name': 'Mana Upgrade Potion', 'effect': 'heal_mana', 'amount': 50}
    }
MATERIALS = {
    'slime_gel': {'name': 'Slime Gel', 'rarity': 'common', 'desc': 'Gelatinous substance from slimes.'},
    'goblin_tooth': {'name': 'Goblin Tooth', 'rarity': 'common', 'desc': 'Sharp tooth from goblins.'},
    'wolf_pelt': {'name': 'Wolf Pelt', 'rarity': 'common', 'desc': 'Fur from wolves.'},
    'skeleton_bone': {'name': 'Skeleton Bone', 'rarity': 'common', 'desc': 'Bone from skeletons.'},
    'orc_iron': {'name': 'Orc Iron', 'rarity': 'common', 'desc': 'Iron forged by orcs.'},
    'bandit_cloth': {'name': 'Bandit Cloth', 'rarity': 'common', 'desc': 'Cloth from bandits.'},
    'troll_core': {'name': 'Troll Core', 'rarity': 'rare', 'desc': 'Core from trolls.'},
    'dark_essence': {'name': 'Dark Essence', 'rarity': 'rare', 'desc': 'Essence of darkness.'},
    'prism_fragment': {'name': 'Prism Fragment', 'rarity': 'rare', 'desc': 'Fragment of a prism.'},
    'void_fragment': {'name': 'Void Fragment', 'rarity': 'rare', 'desc': 'Fragment from the void.'},
    'infinitium_piece': {'name': 'Infinitium Piece', 'rarity': 'rare', 'desc': 'Piece of infinitium.'},
    'soul_shard': {'name': 'Soul Shard', 'rarity': 'rare', 'desc': 'Shard containing souls.'},
    'transcendent_heart': {'name': 'Transcendent Heart', 'rarity': 'rare', 'desc': 'Heart from transcendent beings.'},
    'dragon_scale': {'name': 'Dragon Scale', 'rarity': 'mythical', 'desc': 'Scale from dragons.'},
    'phoenix_feather': {'name': 'Phoenix Feather', 'rarity': 'mythical', 'desc': 'Feather from phoenixes.'},
    'frozen_heart': {'name': 'Frozen Heart', 'rarity': 'mythical', 'desc': 'Heart encased in ice.'},
    'thunder_core': {'name': 'Thunder Core', 'rarity': 'mythical', 'desc': 'Core of thunder.'},
    'holy_light': {'name': 'Holy Light', 'rarity': 'mythical', 'desc': 'Light imbued with holiness.'},
    'demon_horn': {'name': 'Demon Horn', 'rarity': 'mythical', 'desc': 'Horn from demons.'},
    'crystal_shard': {'name': 'Crystal Shard', 'rarity': 'mythical', 'desc': 'Shard of crystal.'},
    'star_dust': {'name': 'Star Dust', 'rarity': 'mythical', 'desc': 'Dust from stars.'},
    'moon_rock': {'name': 'Moon Rock', 'rarity': 'mythical', 'desc': 'Rock from the moon.'},
    'sun_stone': {'name': 'Sun Stone', 'rarity': 'mythical', 'desc': 'Stone powered by the sun.'},
    'spider_venom': {'name': 'Spider Venom', 'rarity': 'common', 'desc': 'Venom from giant spiders.'},
    'stone_core': {'name': 'Stone Core', 'rarity': 'common', 'desc': 'Core from stone golems.'},
    'ice_shard': {'name': 'Ice Shard', 'rarity': 'common', 'desc': 'Shard of ice.'},
    'fire_essence': {'name': 'Fire Essence', 'rarity': 'rare', 'desc': 'Essence of fire.'},
    'lightning_feather': {'name': 'Lightning Feather', 'rarity': 'rare', 'desc': 'Feather charged with lightning.'},
    'shadow_cloak': {'name': 'Shadow Cloak', 'rarity': 'rare', 'desc': 'Cloak woven from shadows.'},
    'arcane_tome': {'name': 'Arcane Tome', 'rarity': 'rare', 'desc': 'Tome of arcane knowledge.'},
    'curse_scroll': {'name': 'Curse Scroll', 'rarity': 'rare', 'desc': 'Scroll with curses.'},
    'ember': {'name': 'Ember', 'rarity': 'rare', 'desc': 'Glowing ember.'},
    'bat_wing': {'name': 'Bat Wing', 'rarity': 'common', 'desc': 'Wing from dark bats.'}
    }
CRAFTABLE_WEAPONS = {
    "forged_goblin_dagger": {"name": "Forged Goblin Dagger", "atk": 8, "price": 0, "score_price": 0, "recipe": {"goblin_tooth": 3, "bandit_cloth": 1}, "type": "weapon", "desc": "Crude goblin dagger."},
    "forged_bone_sword": {"name": "Forged Bone Sword", "atk": 15, "price": 500, "recipe": {"skeleton_bone": 5, "orc_iron": 2}, "type": "weapon", "desc": "Sword made of bones."},
    "forged_troll_hammer": {"name": "Forged Troll Hammer", "atk": 40, "price": 2000, "recipe": {"troll_core": 1, "orc_iron": 3}, "type": "weapon", "desc": "Heavy hammer that hums."},
    "forged_frostblade": {"name": "Forged Frostblade", "atk": 120, "price": 5000, "score_price": 200, "recipe": {"frozen_heart": 2, "ice_shard": 5, "crystal_shard": 3}, "type": "weapon", "desc": "Blade imbued with ice power."},
    "forged_flameblade": {"name": "Forged Flameblade", "atk": 130, "price": 5500, "score_price": 250, "recipe": {"fire_essence": 2, "phoenix_feather": 1, "crystal_shard": 3}, "type": "weapon", "desc": "Blade imbued with fire power."},
    "forged_thunder_sword": {"name": "Forged Thunder Sword", "atk": 150, "price": 7000, "score_price": 400, "recipe": {"thunder_core": 2, "lightning_feather": 3, "crystal_shard": 4}, "type": "weapon", "desc": "Sword crackling with lightning."},
    "forged_holy_avenger": {"name": "Forged Holy Avenger", "atk": 1000, "price": 10000, "score_price": 800, "recipe": {"holy_light": 2, "sun_stone": 2, "moon_rock": 2}, "type": "weapon", "desc": "Blessed sword of light."},
    "forged_dragon_slayer": {"name": "Forged Dragon Slayer", "atk": 2500, "price": 15000, "score_price": 1500, "recipe": {"dragon_scale": 5, "thunder_core": 2, "infinitium_piece": 1}, "type": "weapon", "desc": "Legendary sword for dragon hunting."},
    "forged_cosmic_blade": {"name": "Forged Cosmic Blade", "atk": 5000, "price": 30000, "score_price": 3000, "recipe": {"star_dust": 5, "void_fragment": 3, "infinitium_piece": 2}, "type": "weapon", "desc": "Blade forged from cosmic materials."},
    "forged_transcendent_edge": {"name": "Forged Transcendent Edge", "atk": 6000, "price": 100000, "score_price": 10000, "recipe": {"transcendent_heart": 1, "void_fragment": 5, "infinitium_piece": 3, "soul_shard": 2}, "type": "weapon", "desc": "Weapon beyond mortal comprehension."},
    }

CRAFTABLE_ARMORS = {
    "forged_goblin_armor": {"name": "Forged Goblin Armor", "def": 2, "price": 0, "recipe": {"goblin_tooth": 3, "bandit_cloth": 2}, "type": "armor", "desc": "Crude goblin armor."},
    "forged_bone_armor": {"name": "Forged Bone Armor", "def": 8, "price": 500, "recipe": {"skeleton_bone": 5, "orc_iron": 2}, "type": "armor", "desc": "Armor made of bones."},
    "forged_troll_armor": {"name": "Forged Troll Armor", "def": 20, "price": 2000, "recipe": {"troll_core": 1, "orc_iron": 3}, "type": "armor", "desc": "Heavy armor that regenerates."},
    "forged_frost_armor": {"name": "Forged Frost Armor", "def": 40, "price": 4000, "score_price": 150, "recipe": {"frozen_heart": 2, "ice_shard": 5, "crystal_shard": 3}, "type": "armor", "desc": "Armor imbued with ice power."},
    "forged_flame_armor": {"name": "Forged Flame Armor", "def": 45, "price": 4500, "score_price": 200, "recipe": {"fire_essence": 2, "phoenix_feather": 1, "crystal_shard": 3}, "type": "armor", "desc": "Armor imbued with fire power."},
    "forged_thunder_armor": {"name": "Forged Thunder Armor", "def": 55, "price": 6000, "score_price": 350, "recipe": {"thunder_core": 2, "lightning_feather": 3, "crystal_shard": 4}, "type": "armor", "desc": "Armor crackling with lightning."},
    "forged_holy_armor": {"name": "Forged Holy Armor", "def": 70, "price": 9000, "score_price": 700, "recipe": {"holy_light": 2, "sun_stone": 2, "moon_rock": 2}, "type": "armor", "desc": "Blessed armor of light."},
    "forged_dragon_scale_armor": {"name": "Forged Dragon Scale Armor", "def": 100, "price": 14000, "score_price": 1400, "recipe": {"dragon_scale": 5, "thunder_core": 2, "infinitium_piece": 1}, "type": "armor", "desc": "Legendary armor made of dragon scales."},
    "forged_cosmic_armor": {"name": "Forged Cosmic Armor", "def": 200, "price": 28000, "score_price": 2800, "recipe": {"star_dust": 5, "void_fragment": 3, "infinitium_piece": 2}, "type": "armor", "desc": "Armor forged from cosmic materials."},
    "forged_transcendent_armor": {"name": "Forged Transcendent Armor", "def": 500, "price": 95000, "score_price": 9500, "recipe": {"transcendent_heart": 1, "void_fragment": 5, "infinitium_piece": 3, "soul_shard": 2}, "type": "armor", "desc": "Armor beyond mortal comprehension."},
    }

CRAFTABLE_WANDS = {
    "forged_goblin_wand": {"name": "Forged Goblin Wand", "magic_power": 8, "price": 0, "score_price": 0, "recipe": {"goblin_tooth": 3, "bandit_cloth": 1}, "type": "wand", "desc": "Crude goblin wand."},
    "forged_bone_wand": {"name": "Forged Bone Wand", "magic_power": 15, "price": 500, "recipe": {"skeleton_bone": 5, "orc_iron": 2}, "type": "wand", "desc": "Wand made of bones."},
    "forged_troll_staff": {"name": "Forged Troll Staff", "magic_power": 40, "price": 2000, "recipe": {"troll_core": 1, "orc_iron": 3}, "type": "wand", "desc": "Heavy staff that hums."},
    "forged_frost_wand": {"name": "Forged Frost Wand", "magic_power": 60, "price": 4000, "score_price": 150, "recipe": {"frozen_heart": 2, "ice_shard": 5, "crystal_shard": 3}, "type": "wand", "desc": "Wand imbued with ice power."},
    "forged_flame_wand": {"name": "Forged Flame Wand", "magic_power": 65, "price": 4500, "score_price": 200, "recipe": {"fire_essence": 2, "phoenix_feather": 1, "crystal_shard": 3}, "type": "wand", "desc": "Wand imbued with fire power."},
    "forged_thunder_wand": {"name": "Forged Thunder Wand", "magic_power": 75, "price": 6000, "score_price": 350, "recipe": {"thunder_core": 2, "lightning_feather": 3, "crystal_shard": 4}, "type": "wand", "desc": "Wand crackling with lightning."},
    "forged_holy_scepter": {"name": "Forged Holy Scepter", "magic_power": 90, "price": 9000, "score_price": 700, "recipe": {"holy_light": 2, "sun_stone": 2, "moon_rock": 2}, "type": "wand", "desc": "Blessed scepter of light."},
    "forged_dragon_staff": {"name": "Forged Dragon Staff", "magic_power": 125, "price": 14000, "score_price": 1400, "recipe": {"dragon_scale": 5, "thunder_core": 2, "infinitium_piece": 1}, "type": "wand", "desc": "Legendary staff of dragon power."},
    "forged_cosmic_scepter": {"name": "Forged Cosmic Scepter", "magic_power": 250, "price": 28000, "score_price": 2800, "recipe": {"star_dust": 5, "void_fragment": 3, "infinitium_piece": 2}, "type": "wand", "desc": "Scepter forged from cosmic materials."},
    "forged_transcendent_staff": {"name": "Forged Transcendent Staff", "magic_power": 750, "price": 95000, "score_price": 9500, "recipe": {"transcendent_heart": 1, "void_fragment": 5, "infinitium_piece": 3, "soul_shard": 2}, "type": "wand", "desc": "Staff beyond mortal comprehension."},
    }

CRAFTABLE_ROBES = {
    "forged_goblin_robe": {"name": "Forged Goblin Robe", "magic_def": 2, "price": 0, "recipe": {"goblin_tooth": 2, "bandit_cloth": 3}, "type": "robe", "desc": "Crude goblin robe."},
    "forged_bone_robe": {"name": "Forged Bone Robe", "magic_def": 8, "price": 500, "recipe": {"skeleton_bone": 5, "orc_iron": 2}, "type": "robe", "desc": "Robe made of bones."},
    "forged_troll_robe": {"name": "Forged Troll Robe", "magic_def": 20, "price": 2000, "recipe": {"troll_core": 1, "orc_iron": 3}, "type": "robe", "desc": "Heavy robe that regenerates."},
    "forged_frost_robe": {"name": "Forged Frost Robe", "magic_def": 30, "price": 4000, "score_price": 150, "recipe": {"frozen_heart": 2, "ice_shard": 5, "crystal_shard": 3}, "type": "robe", "desc": "Robe imbued with ice power."},
    "forged_flame_robe": {"name": "Forged Flame Robe", "magic_def": 35, "price": 4500, "score_price": 200, "recipe": {"fire_essence": 2, "phoenix_feather": 1, "crystal_shard": 3}, "type": "robe", "desc": "Robe imbued with fire power."},
    "forged_thunder_robe": {"name": "Forged Thunder Robe", "magic_def": 45, "price": 6000, "score_price": 350, "recipe": {"thunder_core": 2, "lightning_feather": 3, "crystal_shard": 4}, "type": "robe", "desc": "Robe crackling with lightning."},
    "forged_holy_robe": {"name": "Forged Holy Robe", "magic_def": 60, "price": 9000, "score_price": 700, "recipe": {"holy_light": 2, "sun_stone": 2, "moon_rock": 2}, "type": "robe", "desc": "Blessed robe of light."},
    "forged_dragon_robe": {"name": "Forged Dragon Robe", "magic_def": 90, "price": 14000, "score_price": 1400, "recipe": {"dragon_scale": 5, "thunder_core": 2, "infinitium_piece": 1}, "type": "robe", "desc": "Legendary robe of dragon power."},
    "forged_cosmic_robe": {"name": "Forged Cosmic Robe", "magic_def": 180, "price": 28000, "score_price": 2800, "recipe": {"star_dust": 5, "void_fragment": 3, "infinitium_piece": 2}, "type": "robe", "desc": "Robe forged from cosmic materials."},
    "forged_transcendent_robe": {"name": "Forged Transcendent Robe", "magic_def": 450, "price": 95000, "score_price": 9500, "recipe": {"transcendent_heart": 1, "void_fragment": 5, "infinitium_piece": 3, "soul_shard": 2}, "type": "robe", "desc": "Robe beyond mortal comprehension."},
    }

CRAFTABLE_NECKLACES = {
    "health_amulet": {"name": "Health Amulet", "hp_bonus": 20, "price": 500, "recipe": {"slime_gel": 3, "wolf_pelt": 2}, "type": "necklace", "desc": "Amulet that boosts health."},
    "mana_amulet": {"name": "Mana Amulet", "mana_bonus": 15, "price": 600, "recipe": {"crystal_shard": 3, "slime_gel": 2}, "type": "necklace", "desc": "Amulet that boosts mana."},
    "strength_amulet": {"name": "Strength Amulet", "atk_bonus": 5, "price": 700, "recipe": {"goblin_tooth": 3, "wolf_pelt": 2}, "type": "necklace", "desc": "Amulet that boosts attack."},
    "defense_amulet": {"name": "Defense Amulet", "def_bonus": 3, "price": 650, "recipe": {"skeleton_bone": 3, "slime_gel": 2}, "type": "necklace", "desc": "Amulet that boosts defense."},
    "crit_amulet": {"name": "Critical Amulet", "crit_bonus": 10, "price": 800, "recipe": {"bandit_cloth": 3, "crystal_shard": 2}, "type": "necklace", "desc": "Amulet that boosts critical chance."},
    "lifesteal_amulet": {"name": "Lifesteal Amulet", "lifesteal_bonus": 5, "price": 900, "recipe": {"spider_venom": 2, "bat_wing": 2}, "type": "necklace", "desc": "Amulet that provides lifesteal."},
    "forged_frost_necklace": {"name": "Forged Frost Necklace", "magic_def_bonus": 15, "hp_bonus": 30, "price": 3000, "score_price": 100, "recipe": {"frozen_heart": 1, "ice_shard": 3, "crystal_shard": 2}, "type": "necklace", "desc": "Necklace imbued with ice power."},
    "forged_flame_necklace": {"name": "Forged Flame Necklace", "magic_atk_bonus": 10, "atk_bonus": 8, "price": 3500, "score_price": 150, "recipe": {"fire_essence": 1, "phoenix_feather": 1, "crystal_shard": 2}, "type": "necklace", "desc": "Necklace imbued with fire power."},
    "forged_thunder_necklace": {"name": "Forged Thunder Necklace", "crit_bonus": 15, "atk_bonus": 10, "price": 5000, "score_price": 300, "recipe": {"thunder_core": 1, "lightning_feather": 3, "crystal_shard": 2}, "type": "necklace", "desc": "Necklace crackling with lightning."},
    "forged_holy_pendant": {"name": "Forged Holy Pendant", "hp_bonus": 50, "mana_bonus": 30, "def_bonus": 5, "price": 8000, "score_price": 600, "recipe": {"holy_light": 1, "sun_stone": 2, "moon_rock": 2}, "type": "necklace", "desc": "Blessed pendant of light."},
    "forged_dragon_necklace": {"name": "Forged Dragon Necklace", "atk_bonus": 20, "def_bonus": 15, "hp_bonus": 70, "price": 12000, "score_price": 1200, "recipe": {"dragon_scale": 3, "thunder_core": 1, "infinitium_piece": 1}, "type": "necklace", "desc": "Legendary necklace of dragon power."},
    "forged_cosmic_necklace": {"name": "Forged Cosmic Necklace", "magic_atk_bonus": 30, "magic_def_bonus": 25, "mana_bonus": 50, "price": 24000, "score_price": 2400, "recipe": {"star_dust": 3, "void_fragment": 2, "infinitium_piece": 1}, "type": "necklace", "desc": "Necklace forged from cosmic materials."},
    "forged_transcendent_necklace": {"name": "Forged Transcendent Necklace", "atk_bonus": 50, "def_bonus": 40, "hp_bonus": 150, "mana_bonus": 100, "crit_bonus": 20, "lifesteal_bonus": 10, "price": 80000, "score_price": 8000, "recipe": {"transcendent_heart": 1, "void_fragment": 3, "infinitium_piece": 2, "soul_shard": 1}, "type": "necklace", "desc": "Necklace beyond mortal comprehension."},
    }